import { createContext, useContext, useState, useCallback, useEffect } from 'react'

const STORAGE_KEY = 'tradestats_language'
const Ctx = createContext(null)

/* ─── Translation dictionary ───────────────────────────────── */
const TRANSLATIONS = {
  de: {
    // ── App-wide
    'app.privacy':            'Privacy',
    'app.live_mt5_equity':    'Live MT5-Equity',
    'app.starting_capital':   'Anfangs-Kapital',
    'app.starting_capital.hint': 'Sobald MT5 verbunden ist, wird automatisch die Live-Equity übernommen.',
    'app.starting_capital.live_hint': 'ROI-Basis wird automatisch von deinem MT5-Account übernommen — keine manuelle Eingabe nötig.',
    'app.ok':                 'OK',

    // ── Sidebar
    'nav.dashboard':       'Dashboard',
    'nav.journal':         'Trade Journal',
    'nav.daily_journal':   'Daily Journal',
    'nav.calendar':        'Kalender',
    'nav.analyse':         'Analyse',
    'nav.setups':          'Setups',
    'nav.risk':            'Risiko',
    'nav.profile':         'Profil',
    'nav.import':          'Import',
    'nav.export':          'Export',
    'nav.live':            'Live',
    'nav.offline':         'Offline',
    'nav.mt5_disconnected': 'MT5 getrennt',
    'nav.trading_journal': 'Trading Journal',

    // ── Common
    'common.save':         'Speichern',
    'common.saved':        'Gespeichert',
    'common.cancel':       'Abbrechen',
    'common.delete':       'Löschen',
    'common.confirm':      'Bestätigen',
    'common.confirm_q':    'Wirklich löschen?',
    'common.back':         'Zurück',
    'common.close':        'Schließen',
    'common.search':       'Suchen',
    'common.filter':       'Filter',
    'common.reset':        'Zurücksetzen',
    'common.add':          'Hinzufügen',
    'common.edit':         'Bearbeiten',
    'common.copy':         'Kopieren',
    'common.copied':       'Kopiert!',
    'common.download':     'Download',
    'common.upload':       'Hochladen',
    'common.all':          'Alle',
    'common.none':         'Keine',
    'common.from':         'Von',
    'common.to':           'Bis',
    'common.symbol':       'Symbol',
    'common.type':         'Typ',
    'common.volume':       'Volumen',
    'common.volume_short': 'Vol.',
    'common.price':        'Preis',
    'common.entry':        'Entry',
    'common.exit':         'Exit',
    'common.open':         'Open',
    'common.current':      'Aktuell',
    'common.duration':     'Dauer',
    'common.pnl':          'P&L',
    'common.profit':       'Gewinn',
    'common.loss':         'Verlust',
    'common.trades':       'Trades',
    'common.trade':        'Trade',
    'common.win_rate':     'Win Rate',
    'common.profit_factor':'Profit Faktor',
    'common.notes':        'Notizen',
    'common.tags':         'Tags',
    'common.tag':          'Tag',
    'common.date':         'Datum',
    'common.day':          'Tag',
    'common.week':         'Woche',
    'common.month':        'Monat',
    'common.year':         'Jahr',
    'common.all_time':     'Alles',
    'common.today':        'Heute',
    'common.yesterday':    'Gestern',
    'common.this_week':    'Diese Woche',
    'common.last_week':    'Letzte Woche',
    'common.this_month':   'Dieser Monat',
    'common.last_month':   'Letzter Monat',
    'common.this_year':    'Dieses Jahr',
    'common.last_year':    'Letztes Jahr',
    'common.all_times':    'Alle Zeiten',
    'common.generated_at': 'Generiert am',
    'common.last_update':  'Letztes Update',
    'common.never':        'Nie',
    'common.no_trades':    'Keine Trades vorhanden',
    'common.no_trades_found': 'Keine Trades gefunden',
    'common.no_data':      'Keine Daten',
    'common.loading':      'Lade...',
    'common.failed':       'Fehlgeschlagen',
    'common.success':      'Erfolgreich',
    'common.preview':      'Vorschau',
    'common.timeframe':    'Zeitraum',
    'common.trading_days': 'Trading-Tage',
    'common.connected':    'verbunden',
    'common.not_connected':'nicht verbunden',
    'common.position':     'Position',
    'common.positions':    'Positionen',

    // ── Trade Journal
    'journal.title':          'Trade Journal',
    'journal.add_trade':      'Trade hinzufügen',
    'journal.sync':           'Sync',
    'journal.syncing':        'Synchronisiere…',
    'journal.search_placeholder': 'Suche nach Symbol, Notiz, Tag...',
    'journal.more_filters':   'Mehr Filter',
    'journal.groups_detected':'erkannt',
    'journal.x_of_y_filtered':'{shown} von {total} Trades gefiltert',
    'journal.selected':       '{count} ausgewählt',
    'journal.deselect':       'Aufheben',
    'journal.bulk_delete':    'Löschen',
    'journal.delete_trade':   'Trade löschen',
    'journal.delete_confirm': 'Trade wirklich löschen?',
    'journal.trade_deleted':  'Trade gelöscht',
    'journal.trades_deleted': '{count} Trades gelöscht',
    'journal.undo':           'Rückgängig',
    'journal.undo_hint':      'Klick auf Rückgängig zum Wiederherstellen',
    'journal.dissolve_group': 'Gruppe auflösen',
    'journal.remove_from_group': 'Aus Gruppe entfernen',
    'journal.no_autogroup':   'Nicht auto-gruppieren',
    'journal.enable_autogroup': 'Auto-Group aktivieren',
    'journal.drag_hint':      'Trades per Drag & Drop manuell gruppieren — einfach eine Zeile auf eine andere ziehen.',
    'journal.col_avg_entry':  'Ø Entry',
    'journal.col_avg_exit':   'Ø Exit',
    'journal.symbol_choose':  'Symbol wählen',
    'journal.cat_all':         'Alle',
    'journal.cat_forex':       'Forex',
    'journal.cat_commodities': 'Commodities',
    'journal.cat_indices':     'Indices',
    'journal.cat_crypto':      'Crypto',
    'journal.cat_stocks':      'Aktien',
    'journal.tag_all':         'Alle Tags',
    'journal.sync_done':       'Sync erfolgreich',
    'journal.sync_failed':     'Synchronisierung fehlgeschlagen',
    'journal.sync_already_up_to_date': 'Bereits aktuell',
    'journal.sync_updated':    '{count} aktualisiert',
    'journal.sync_new':        '{count} neu',
    'journal.sync_x_from_mt5': '{parts} aus MT5',
    'journal.sync_x_in_backend': '{count} Trades im Backend, alle synchron',
    'journal.manual':         'manuell',
    'journal.select_all':     'Alle auswählen',
    'journal.groups':         'Gruppen',

    // ── Trade Detail Modal
    'modal.opened':          'Geöffnet',
    'modal.closed':          'Geschlossen',
    'modal.new_tag':         'Neuer Tag...',
    'modal.mark_mistakes':   'Fehler markieren (optional, ehrlich sein zahlt sich aus)',
    'modal.mistakes_hint':   'Diese Markierungen fließen in die Fehler-Kosten-Analyse auf der Analyse-Seite ein.',
    'modal.notes_placeholder': 'Trade-Analyse, Emotionen, Verbesserungen...',
    'modal.setup_label':     'Setup',
    'modal.no_setup':        '— Kein Setup zugeordnet —',
    'modal.setup_target_rr': 'Ziel R:R',
    'modal.opening':         'Eröffnung',
    'modal.closing':         'Schluss',
    'modal.lot':             'Lot',
    'modal.stop_loss':       'Stop Loss',
    'modal.take_profit':     'Take Profit',
    'modal.commission':      'Kommission',
    'modal.swap':            'Swap',
    'modal.gross_profit':    'Rohgewinn',
    'modal.net_pnl':         'Netto P&L',

    // ── Add Trade Modal
    'add.title':             'Trade hinzufügen',
    'add.commission':        'Kommission',
    'add.swap':              'Swap',
    'add.add_trade':         'Trade hinzufügen',

    // ── Live Sync Panel
    'live.open_positions':   'Offene Positionen',
    'live.groups':           '{count} Gruppe',
    'live.groups_plural':    '{count} Gruppen',
    'live.no_positions':     'Keine offenen Positionen',
    'live.mt5_connected':    'TMGM MT5 verbunden',
    'live.mt5_not_connected':'MT5 nicht verbunden',
    'live.connection_info':  '{trade_count} Trades · {pos_count} Position',
    'live.col_risk_reward':  'Risk/Reward',
    'live.position_note':    'Position-Notiz',
    'live.note_placeholder': 'Warum bin ich eingestiegen? Setup, Bias, Levels...',
    'live.add_tag':          'Tag hinzufügen...',
    'live.account':          'Account',
    'live.balance':          'Balance',
    'live.equity':           'Equity',
    'live.open_pnl':         'Offener P&L',
    'live.margin_level':     'Margin Level',
    'live.x_imported':       '{count} Trade importiert',
    'live.x_imported_plural':'{count} Trades importiert',
    'live.auto_imported':    'Automatisch aus MT5 synchronisiert',

    // ── Setup Library
    'setups.title':            'Setup-Bibliothek',
    'setups.subtitle':         'Deine Trading-Playbooks',
    'setups.setups_defined':   '{count} Setup definiert',
    'setups.setups_defined_plural': '{count} Setups definiert',
    'setups.unassigned':       '{count} Trades noch nicht zugeordnet',
    'setups.new_setup':        'Neues Setup',
    'setups.edit_setup':       'Setup bearbeiten',
    'setups.no_setups':        'Noch keine Setups definiert',
    'setups.no_setups_hint':   'Lege deine Trading-Setups als wiederverwendbare Playbooks an. Jeder Trade kann später einem Setup zugeordnet werden, damit du siehst, welche deiner Strategien wirklich Geld bringen.',
    'setups.field_name':       'Name',
    'setups.field_color':      'Farbe',
    'setups.field_description':'Beschreibung',
    'setups.desc_placeholder': 'In welcher Marktphase setzt du das? Was ist die These?',
    'setups.field_target_rr':  'Ziel R:R',
    'setups.field_max_risk':   'Max Risiko %',
    'setups.entry_rules':      'Entry-Regeln',
    'setups.exit_rules':       'Exit-Regeln',
    'setups.entry_placeholder':'z.B. Preis über Tages-VWAP',
    'setups.exit_placeholder': 'z.B. SL unter letztem Tief',
    'setups.add_rule':         'Regel hinzufügen',
    'setups.create':           'Setup anlegen',
    'setups.delete_confirm':   'Setup "{name}" wirklich löschen?',
    'setups.entry_section':    'Entry:',
    'setups.exit_section':     'Exit:',
    'setups.more_rules':       '… +{count} mehr',
    'setups.risk':             'Risiko',

    // ── Profile / Share
    'profile.title':            'Profil',
    'profile.subtitle':         'Teile deine Trading-Performance — ohne absolute Dollarbeträge',
    'profile.share_export':     'Teilen & Exportieren',
    'profile.copy_image':       'Bild in Zwischenablage',
    'profile.image_copied':     'Bild kopiert!',
    'profile.creating_image':   'Erstelle Bild…',
    'profile.copy_image_hint':  'PNG direkt in Zwischenablage — perfekt zum Posten',
    'profile.paste_hint':       'Mit Ctrl+V in Discord, Telegram etc. einfügen',
    'profile.download_png':     'PNG herunterladen',
    'profile.download_png_hint':'Speichert die Share-Card als hochauflösendes Bild',
    'profile.copy_link':        'Link kopieren',
    'profile.link_copied':      'Link kopiert!',
    'profile.copy_link_hint':   'URL mit Base64-codierten Stats — Read-Only-Ansicht',
    'profile.export_pdf':       'PDF exportieren',
    'profile.export_pdf_hint':  'Druckt nur die Share-Card, ohne Navigation',
    'profile.share_safe_hint':  'Bild, PDF & Link enthalten keine absoluten Dollarbeträge.',
    'profile.no_dollar':        'Keine absoluten Dollarbeträge',
    'profile.included_metrics': 'Enthaltene Metriken',
    'profile.no_trades_in_period':'Keine Trades in diesem Zeitraum',
    'profile.review_day':       'Tagesrückblick',
    'profile.review_week':      'Wochenrückblick',
    'profile.review_month':     'Monatsrückblick',
    'profile.review_year':      'Jahresrückblick',
    'profile.review_all':       'Gesamt-Performance',
    'profile.best_trade':       'Bester Trade',
    'profile.top_n_trades':     'Top {count} Trade',
    'profile.top_n_trades_plural':'Top {count} Trades',
    'profile.avg_trades_day':   'Ø Trades/Tag',
    'profile.go_to_today':      'Zurück zur aktuellen Periode',
    'profile.prev_day':         'Vorheriger Tag',
    'profile.prev_week':        'Vorherige Woche',
    'profile.prev_month':       'Vorheriger Monat',
    'profile.prev_year':        'Vorheriges Jahr',
    'profile.next_period':      'Nächste Periode',
    'profile.future':           'Zukunft',
    // Mentor brief
    'mb.title':                 'Mentor-Brief',
    'mb.subtitle':              'Strukturierte Performance-Zusammenfassung zum Teilen mit Coach/AI-Mentor.',
    'mb.privacy_mode':          'Privacy-Modus',
    'mb.privacy_full':          'Voll',
    'mb.privacy_full_desc':     '$ Beträge',
    'mb.privacy_relative':      'R-Multiples',
    'mb.privacy_relative_desc': 'Risiko-relativ',
    'mb.privacy_anonymous':     'Anonym',
    'mb.privacy_anonymous_desc':'Nur Ratios',
    'mb.share_notes':           'Notizen mit teilen',
    'mb.focus_label':           'Fokus für die Session (optional)',
    'mb.focus_placeholder':     "Worüber willst du reden? z.B. 'Warum überhandle ich nach Lossern? Welches Setup soll ich streichen?'",
    'mb.generate':              'Brief generieren',
    'mb.copy_md':               'Markdown kopieren',
    'mb.copy_md_done':          'Kopiert!',
    'mb.show_preview':          'Vorschau anzeigen',
    // Backup
    'backup.title':             'Backup & Wiederherstellung',
    'backup.subtitle':          'Alle Trades, Tags, Gruppen & Notizen liegen lokal im Browser — JSON-Export schützt vor Datenverlust.',
    'backup.export':            'Backup exportieren (JSON)',
    'backup.export_hint':       '{trades} Trades, {notes} Position-Notizen',
    'backup.restore':           'Backup wiederherstellen',
    'backup.restore_hint':      'Überschreibt aktuelle Trades, Tags und Notizen',
    'backup.restore_confirm':   'Backup wiederherstellen?',
    'backup.restore_file':      'Datei',
    'backup.restore_exported':  'Exportiert',
    'backup.restore_trades_in_backup': 'Trades im Backup',
    'backup.restore_warning':   'Achtung: Aktuelle Trades, Tags, Gruppen und Notizen werden komplett überschrieben. Sicher dass du fortfahren willst?',
    'backup.restore_action':    'Wiederherstellen',

    // ── Dashboard / Analyse common
    'dash.equity_curve':        'Equity Kurve',
    'dash.monthly_pnl':         'Monatlicher P&L',
    'dash.drawdown':            'Drawdown',
    'dash.hold_duration':       'Ø Haltedauer nach Symbol',
    'dash.pnl_by_symbol':       'P&L nach Symbol',
    'dash.total_pnl':           'Gesamt P&L',
    'dash.roi':                 'ROI',
    'dash.avg_rr':              'Ø R:R',
    'dash.basis':               'Basis',
    'dash.winners':             '{count} Gewinner',
    'dash.choose_timeframe':    'Zeitraum auswählen',
    'dash.apply':               'Anwenden',
    'dash.choose_date':         'Eigenen Zeitraum wählen',
    'dash.date_short':          'Datum',
    'dash.tf_1d':               '1T',
    'dash.tf_1w':               '1W',
    'dash.tf_1m':               '1M',
    'dash.tf_3m':               '3M',
    'dash.tf_6m':               '6M',
    'dash.tf_1y':               '1J',
    'dash.tf_all':              'Alles',
    'dash.x_of_y_filtered':     '{shown} von {total} Trades gefiltert',
    'dash.x_trades_pos_grouped':'({positions} Positionen, {groups} gruppiert)',
    'dash.excellent':           'Exzellent',
    'dash.good':                'Gut',
    'dash.bad':                 'Schlecht',
    'dash.improve':             'Verbesserung',
    'dash.basis_label':         'Basis',
    'dash.win_rate':            'Win Rate',
    'dash.trades_label':        'Trades',
    'dash.symbol_col':          'Symbol',
    'dash.winners_col':         'Gewinner',
    'dash.pnl':                 'P&L',

    // ── Risk
    'risk.title':               'Risiko-Analyse',
    'risk.based_on':            'Basierend auf {pct}% Risiko pro Trade',
    'risk.avg_risk':            'Ø Risiko pro Trade',
    'risk.max_risk':            'Max. Risiko pro Trade',
    'risk.fixed_model':         'Fixiertes Risiko-Modell',
    'risk.avg_r_multiple':      'Ø R-Multiple',
    'risk.expectancy_positive': 'Profitabler Erwartungswert',
    'risk.expectancy_negative': 'Erwartungswert negativ',
    'risk.r_distribution':      'R-Multiple Verteilung',
    'risk.all_trades':          'Alle Trades',
    'risk.tilt_detector':       'Tilt-Detektor',
    'risk.tilt_subtitle':       'Verhalten nach Verlust-Serien',
    'risk.tilt_need_data':      'Mindestens 5 Trades nach Gewinn-Phasen nötig, um eine Baseline zu berechnen — aktuell {count}.',
    'risk.tilt_normal':         'Normalzustand',
    'risk.tilt_normal_desc':    'Nach Gewinn / Start',
    'risk.tilt_one_loss':       '1 Loser davor',
    'risk.tilt_first_loss':     'Erste Niederlage',
    'risk.tilt_two_losses':     '2 Loser davor',
    'risk.tilt_frustzone':      'Frust zone',
    'risk.tilt_three_plus':     '3+ Loser davor',
    'risk.tilt_zone':           'Tilt-Bereich',
    'risk.tilt_too_little_data':'Zu wenig Daten',
    'risk.tilt_no_pattern':     'Kein Tilt-Muster erkennbar — du behältst die Disziplin nach Verlust-Serien. Stark.',
    'risk.avg_volume':          'Ø Volumen',
    'risk.avg_pnl':             'Ø P&L',
    'risk.avg_r':               'Ø R',

    // ── Analyse Section Titles
    'an.title':                 'Analyse',
    'an.subtitle':              '{count} tiefe Auswertungen — basierend auf {trades} Trades.',
    'an.empty':                 'Noch keine abgeschlossenen Trades — sobald welche da sind, lebt diese Seite auf.',
    'an.forecast':              'Equity-Prognose',
    'an.forecast_subtitle':     'Wenn dein Schnitt der letzten {range} so weiterläuft.',
    'an.coach':                 'Coach-Mode — Wochenrückblick',
    'an.coach_subtitle':        'Woche ab {date} · vs. Vorwoche',
    'an.yearly':                'Trading-Jahr auf einen Blick',
    'an.pareto':                'Pareto-Analyse: Wer trägt deinen Account?',
    'an.whatif':                'Was-wäre-wenn-Simulator',
    'an.holdtime':              'Hold-Time vs. Ergebnis',
    'an.best_vs_worst':         'Best vs Worst — die 10 Besten gegen die 10 Schlechtesten',
    'an.streak':                'Streak-Statistik',
    'an.sequence':              'Sequenz-Bias / Revenge-Trading',
    'an.heatmap':               'Performance-Heatmap (Tag × Stunde)',
    'an.mfe_mae':               'MFE/MAE-Capture-Rate',
    'an.mistakes':              'Fehler-Kosten-Analyse',
    'an.ulcer':                 'Ulcer-Index & Recovery',
    'an.recovery':              'Recovery Factor',
    'an.ror':                   'Risk-of-Ruin & Kelly-Fraction',
    'an.tag_matrix':            'Tag-Kombi-Matrix',
    'an.vol_norm':              'Volatilitäts-normalisierte Returns',
    'an.consistency':           'Konsistenz-Score',
    // Forecast controls
    'fc.basis':                 'Basis',
    'fc.mode':                  'Modus',
    'fc.compound':              'Zinseszins',
    'fc.linear':                'Linear',
    'fc.forecast':              'Prognose',
    'fc.target':                'Tagesziel',
    'fc.workday':               '/ Werktag',
    'fc.disable_target':        'Tagesziel deaktivieren',
    'fc.avg_return_day':        'Ø Rendite / Tag',
    'fc.avg_pnl_day':           'Ø P&L / Tag',
    'fc.current_equity':        'Aktuelle Equity',
    'fc.in_x_days':             'In {days} Tagen',
    'fc.expected_return':       'Erwartete Rendite',
    'fc.x_trading_days':        '{count} Trading-Tage',
    'fc.vs_balance':            'vs. {label} ${value}',
    'fc.starting_capital':      'Startkapital',
    'fc.mt5_equity':            'MT5-Equity',
    'fc.if_pace_continues':     'Wenn das Tempo so bleibt — Ziele',
    'fc.doubling':              'Verdopplung',
    'fc.plus_25':               '+25%',
    'fc.next_1k':               'Nächste $1k-Marke',
    'fc.reached':               '✓ erreicht',
    'fc.x_days':                '{days} Tage',
    'fc.x_years':                '{years} Jahre',
    'fc.negative_pace':         'Aktuelle Performance ist negativ — bei diesem Tempo schmilzt der Account. Wechsel zur größeren Basis ({all}) für ein realistischeres Bild oder fix erst die Strategie.',
    'fc.legend_actual':         'Tatsächliche Equity',
    'fc.legend_forecast':       'Prognose (Schnitt der letzten {range})',
    'fc.legend_target':         'Ziel ({pct}% / Werktag, Wochenenden flach)',
    'fc.confidence_band':       'Schattierter Bereich = ±1σ Vertrauensband (~68% der Pfade liegen drin).',
    'fc.compound_note':         'Zinseszins-Modus: tägliche Rendite wird auf das wachsende Equity angewendet.',
    'fc.linear_note':           'Linear-Modus: fester Dollar-Betrag pro Tag, kein Reinvestment.',
    'fc.ahead_of_target':       '{pct}% über Ziel',
    'fc.behind_target':         '{pct}% hinter Ziel',
    'fc.target_explainer':      'Bei {pct}% pro Werktag müsstest du jetzt bei ${target} stehen, bist aber bei ${current}. · Ziel in {days} Tagen: ${final}',

    // Other Analyse sub-strings & badges
    'an.now':                   'Jetzt',
    'an.start':                 'Start',
  },
  en: {
    // ── App-wide
    'app.privacy':            'Privacy',
    'app.live_mt5_equity':    'Live MT5 equity',
    'app.starting_capital':   'Starting capital',
    'app.starting_capital.hint': 'Once MT5 is connected, the live equity is used automatically.',
    'app.starting_capital.live_hint': 'ROI base is taken directly from your MT5 account — no manual entry needed.',
    'app.ok':                 'OK',

    // ── Sidebar
    'nav.dashboard':       'Dashboard',
    'nav.journal':         'Trade Journal',
    'nav.daily_journal':   'Daily Journal',
    'nav.calendar':        'Calendar',
    'nav.analyse':         'Analysis',
    'nav.setups':          'Setups',
    'nav.risk':            'Risk',
    'nav.profile':         'Profile',
    'nav.import':          'Import',
    'nav.export':          'Export',
    'nav.live':            'Live',
    'nav.offline':         'Offline',
    'nav.mt5_disconnected':'MT5 disconnected',
    'nav.trading_journal': 'Trading Journal',

    // ── Common
    'common.save':         'Save',
    'common.saved':        'Saved',
    'common.cancel':       'Cancel',
    'common.delete':       'Delete',
    'common.confirm':      'Confirm',
    'common.confirm_q':    'Really delete?',
    'common.back':         'Back',
    'common.close':        'Close',
    'common.search':       'Search',
    'common.filter':       'Filter',
    'common.reset':        'Reset',
    'common.add':          'Add',
    'common.edit':         'Edit',
    'common.copy':         'Copy',
    'common.copied':       'Copied!',
    'common.download':     'Download',
    'common.upload':       'Upload',
    'common.all':          'All',
    'common.none':         'None',
    'common.from':         'From',
    'common.to':           'To',
    'common.symbol':       'Symbol',
    'common.type':         'Type',
    'common.volume':       'Volume',
    'common.volume_short': 'Vol.',
    'common.price':        'Price',
    'common.entry':        'Entry',
    'common.exit':         'Exit',
    'common.open':         'Open',
    'common.current':      'Current',
    'common.duration':     'Duration',
    'common.pnl':          'P&L',
    'common.profit':       'Profit',
    'common.loss':         'Loss',
    'common.trades':       'Trades',
    'common.trade':        'Trade',
    'common.win_rate':     'Win Rate',
    'common.profit_factor':'Profit Factor',
    'common.notes':        'Notes',
    'common.tags':         'Tags',
    'common.tag':          'Tag',
    'common.date':         'Date',
    'common.day':          'Day',
    'common.week':         'Week',
    'common.month':        'Month',
    'common.year':         'Year',
    'common.all_time':     'All',
    'common.today':        'Today',
    'common.yesterday':    'Yesterday',
    'common.this_week':    'This week',
    'common.last_week':    'Last week',
    'common.this_month':   'This month',
    'common.last_month':   'Last month',
    'common.this_year':    'This year',
    'common.last_year':    'Last year',
    'common.all_times':    'All time',
    'common.generated_at': 'Generated on',
    'common.last_update':  'Last update',
    'common.never':        'Never',
    'common.no_trades':    'No trades yet',
    'common.no_trades_found': 'No trades found',
    'common.no_data':      'No data',
    'common.loading':      'Loading...',
    'common.failed':       'Failed',
    'common.success':      'Success',
    'common.preview':      'Preview',
    'common.timeframe':    'Period',
    'common.trading_days': 'Trading days',
    'common.connected':    'connected',
    'common.not_connected':'not connected',
    'common.position':     'position',
    'common.positions':    'positions',

    // ── Trade Journal
    'journal.title':          'Trade Journal',
    'journal.add_trade':      'Add trade',
    'journal.sync':           'Sync',
    'journal.syncing':        'Syncing…',
    'journal.search_placeholder': 'Search by symbol, note, tag...',
    'journal.more_filters':   'More filters',
    'journal.groups_detected':'detected',
    'journal.x_of_y_filtered':'{shown} of {total} trades filtered',
    'journal.selected':       '{count} selected',
    'journal.deselect':       'Deselect',
    'journal.bulk_delete':    'Delete',
    'journal.delete_trade':   'Delete trade',
    'journal.delete_confirm': 'Really delete this trade?',
    'journal.trade_deleted':  'Trade deleted',
    'journal.trades_deleted': '{count} trades deleted',
    'journal.undo':           'Undo',
    'journal.undo_hint':      'Click Undo to restore',
    'journal.dissolve_group': 'Dissolve group',
    'journal.remove_from_group': 'Remove from group',
    'journal.no_autogroup':   'Do not auto-group',
    'journal.enable_autogroup': 'Enable auto-group',
    'journal.drag_hint':      'Group trades manually via drag & drop — just drag one row onto another.',
    'journal.col_avg_entry':  'Avg Entry',
    'journal.col_avg_exit':   'Avg Exit',
    'journal.symbol_choose':  'Choose symbol',
    'journal.cat_all':         'All',
    'journal.cat_forex':       'Forex',
    'journal.cat_commodities': 'Commodities',
    'journal.cat_indices':     'Indices',
    'journal.cat_crypto':      'Crypto',
    'journal.cat_stocks':      'Stocks',
    'journal.tag_all':         'All tags',
    'journal.sync_done':       'Sync successful',
    'journal.sync_failed':     'Sync failed',
    'journal.sync_already_up_to_date': 'Already up to date',
    'journal.sync_updated':    '{count} updated',
    'journal.sync_new':        '{count} new',
    'journal.sync_x_from_mt5': '{parts} from MT5',
    'journal.sync_x_in_backend': '{count} trades in backend, all in sync',
    'journal.manual':         'manual',
    'journal.select_all':     'Select all',
    'journal.groups':         'Groups',

    // ── Trade Detail Modal
    'modal.opened':          'Opened',
    'modal.closed':          'Closed',
    'modal.new_tag':         'New tag...',
    'modal.mark_mistakes':   'Mark mistakes (optional — honesty pays off)',
    'modal.mistakes_hint':   'These markers feed into the mistake-cost analysis on the Analysis page.',
    'modal.notes_placeholder': 'Trade analysis, emotions, improvements...',
    'modal.setup_label':     'Setup',
    'modal.no_setup':        '— No setup assigned —',
    'modal.setup_target_rr': 'Target R:R',
    'modal.opening':         'Open',
    'modal.closing':         'Close',
    'modal.lot':             'Lot',
    'modal.stop_loss':       'Stop Loss',
    'modal.take_profit':     'Take Profit',
    'modal.commission':      'Commission',
    'modal.swap':            'Swap',
    'modal.gross_profit':    'Gross profit',
    'modal.net_pnl':         'Net P&L',

    // ── Add Trade Modal
    'add.title':             'Add trade',
    'add.commission':        'Commission',
    'add.swap':              'Swap',
    'add.add_trade':         'Add trade',

    // ── Live Sync Panel
    'live.open_positions':   'Open Positions',
    'live.groups':           '{count} group',
    'live.groups_plural':    '{count} groups',
    'live.no_positions':     'No open positions',
    'live.mt5_connected':    'TMGM MT5 connected',
    'live.mt5_not_connected':'MT5 not connected',
    'live.connection_info':  '{trade_count} trades · {pos_count} position',
    'live.col_risk_reward':  'Risk/Reward',
    'live.position_note':    'Position note',
    'live.note_placeholder': 'Why did I enter? Setup, bias, levels...',
    'live.add_tag':          'Add tag...',
    'live.account':          'Account',
    'live.balance':          'Balance',
    'live.equity':           'Equity',
    'live.open_pnl':         'Open P&L',
    'live.margin_level':     'Margin Level',
    'live.x_imported':       '{count} trade imported',
    'live.x_imported_plural':'{count} trades imported',
    'live.auto_imported':    'Automatically synced from MT5',

    // ── Setup Library
    'setups.title':            'Setup Library',
    'setups.subtitle':         'Your trading playbooks',
    'setups.setups_defined':   '{count} setup defined',
    'setups.setups_defined_plural': '{count} setups defined',
    'setups.unassigned':       '{count} trades not yet assigned',
    'setups.new_setup':        'New setup',
    'setups.edit_setup':       'Edit setup',
    'setups.no_setups':        'No setups defined yet',
    'setups.no_setups_hint':   'Define your trading setups as reusable playbooks. Each trade can later be assigned to a setup so you can see which strategies actually make money.',
    'setups.field_name':       'Name',
    'setups.field_color':      'Color',
    'setups.field_description':'Description',
    'setups.desc_placeholder': 'In which market phase do you use this? What is the thesis?',
    'setups.field_target_rr':  'Target R:R',
    'setups.field_max_risk':   'Max risk %',
    'setups.entry_rules':      'Entry rules',
    'setups.exit_rules':       'Exit rules',
    'setups.entry_placeholder':'e.g. Price above daily VWAP',
    'setups.exit_placeholder': 'e.g. SL below last low',
    'setups.add_rule':         'Add rule',
    'setups.create':           'Create setup',
    'setups.delete_confirm':   'Really delete setup "{name}"?',
    'setups.entry_section':    'Entry:',
    'setups.exit_section':     'Exit:',
    'setups.more_rules':       '… +{count} more',
    'setups.risk':             'Risk',

    // ── Profile / Share
    'profile.title':            'Profile',
    'profile.subtitle':         'Share your trading performance — no absolute dollar amounts',
    'profile.share_export':     'Share & Export',
    'profile.copy_image':       'Copy image to clipboard',
    'profile.image_copied':     'Image copied!',
    'profile.creating_image':   'Creating image…',
    'profile.copy_image_hint':  'PNG to clipboard — perfect for posting',
    'profile.paste_hint':       'Paste with Ctrl+V into Discord, Telegram, etc.',
    'profile.download_png':     'Download PNG',
    'profile.download_png_hint':'Saves the share card as a high-resolution image',
    'profile.copy_link':        'Copy link',
    'profile.link_copied':      'Link copied!',
    'profile.copy_link_hint':   'URL with Base64-encoded stats — read-only view',
    'profile.export_pdf':       'Export PDF',
    'profile.export_pdf_hint':  'Prints only the share card, no navigation',
    'profile.share_safe_hint':  'Image, PDF & link contain no absolute dollar amounts.',
    'profile.no_dollar':        'No absolute dollar amounts',
    'profile.included_metrics': 'Included metrics',
    'profile.no_trades_in_period':'No trades in this period',
    'profile.review_day':       'Daily review',
    'profile.review_week':      'Weekly review',
    'profile.review_month':     'Monthly review',
    'profile.review_year':      'Yearly review',
    'profile.review_all':       'Overall performance',
    'profile.best_trade':       'Best trade',
    'profile.top_n_trades':     'Top {count} Trade',
    'profile.top_n_trades_plural':'Top {count} Trades',
    'profile.avg_trades_day':   'Avg trades/day',
    'profile.go_to_today':      'Back to current period',
    'profile.prev_day':         'Previous day',
    'profile.prev_week':        'Previous week',
    'profile.prev_month':       'Previous month',
    'profile.prev_year':        'Previous year',
    'profile.next_period':      'Next period',
    'profile.future':           'Future',
    'mb.title':                 'Mentor Brief',
    'mb.subtitle':              'Structured performance summary to share with coach/AI mentor.',
    'mb.privacy_mode':          'Privacy mode',
    'mb.privacy_full':          'Full',
    'mb.privacy_full_desc':     '$ amounts',
    'mb.privacy_relative':      'R-multiples',
    'mb.privacy_relative_desc': 'Risk-relative',
    'mb.privacy_anonymous':     'Anonymous',
    'mb.privacy_anonymous_desc':'Ratios only',
    'mb.share_notes':           'Share notes',
    'mb.focus_label':           'Focus for the session (optional)',
    'mb.focus_placeholder':     "What do you want to talk about? e.g. 'Why do I overtrade after losses? Which setup should I drop?'",
    'mb.generate':              'Generate brief',
    'mb.copy_md':               'Copy markdown',
    'mb.copy_md_done':          'Copied!',
    'mb.show_preview':          'Show preview',
    'backup.title':             'Backup & Restore',
    'backup.subtitle':          'All trades, tags, groups & notes live locally in your browser — JSON export protects against data loss.',
    'backup.export':            'Export backup (JSON)',
    'backup.export_hint':       '{trades} trades, {notes} position notes',
    'backup.restore':           'Restore backup',
    'backup.restore_hint':      'Overwrites current trades, tags and notes',
    'backup.restore_confirm':   'Restore backup?',
    'backup.restore_file':      'File',
    'backup.restore_exported':  'Exported',
    'backup.restore_trades_in_backup': 'Trades in backup',
    'backup.restore_warning':   'Warning: current trades, tags, groups and notes will be completely overwritten. Are you sure you want to continue?',
    'backup.restore_action':    'Restore',

    // ── Dashboard / Analyse common
    'dash.equity_curve':        'Equity Curve',
    'dash.monthly_pnl':         'Monthly P&L',
    'dash.drawdown':            'Drawdown',
    'dash.hold_duration':       'Avg Hold by Symbol',
    'dash.pnl_by_symbol':       'P&L by Symbol',
    'dash.total_pnl':           'Total P&L',
    'dash.roi':                 'ROI',
    'dash.avg_rr':              'Avg R:R',
    'dash.basis':               'Base',
    'dash.winners':             '{count} winners',
    'dash.choose_timeframe':    'Choose timeframe',
    'dash.apply':               'Apply',
    'dash.choose_date':         'Choose custom range',
    'dash.date_short':          'Date',
    'dash.tf_1d':               '1D',
    'dash.tf_1w':               '1W',
    'dash.tf_1m':               '1M',
    'dash.tf_3m':               '3M',
    'dash.tf_6m':               '6M',
    'dash.tf_1y':               '1Y',
    'dash.tf_all':              'All',
    'dash.x_of_y_filtered':     '{shown} of {total} trades filtered',
    'dash.x_trades_pos_grouped':'({positions} positions, {groups} grouped)',
    'dash.excellent':           'Excellent',
    'dash.good':                'Good',
    'dash.bad':                 'Bad',
    'dash.improve':             'Improve',
    'dash.basis_label':         'Basis',
    'dash.win_rate':            'Win Rate',
    'dash.trades_label':        'Trades',
    'dash.symbol_col':          'Symbol',
    'dash.winners_col':         'Winners',
    'dash.pnl':                 'P&L',

    // ── Risk
    'risk.title':               'Risk Analysis',
    'risk.based_on':            'Based on {pct}% risk per trade',
    'risk.avg_risk':            'Avg risk per trade',
    'risk.max_risk':            'Max risk per trade',
    'risk.fixed_model':         'Fixed risk model',
    'risk.avg_r_multiple':      'Avg R-multiple',
    'risk.expectancy_positive': 'Profitable expectancy',
    'risk.expectancy_negative': 'Negative expectancy',
    'risk.r_distribution':      'R-multiple distribution',
    'risk.all_trades':          'All trades',
    'risk.tilt_detector':       'Tilt detector',
    'risk.tilt_subtitle':       'Behavior after loss streaks',
    'risk.tilt_need_data':      'At least 5 trades after winning phases needed for baseline — currently {count}.',
    'risk.tilt_normal':         'Baseline',
    'risk.tilt_normal_desc':    'After win / start',
    'risk.tilt_one_loss':       '1 loss before',
    'risk.tilt_first_loss':     'First defeat',
    'risk.tilt_two_losses':     '2 losses before',
    'risk.tilt_frustzone':      'Frustration zone',
    'risk.tilt_three_plus':     '3+ losses before',
    'risk.tilt_zone':           'Tilt zone',
    'risk.tilt_too_little_data':'Too little data',
    'risk.tilt_no_pattern':     'No tilt pattern detected — you keep discipline after loss streaks. Strong.',
    'risk.avg_volume':          'Avg volume',
    'risk.avg_pnl':             'Avg P&L',
    'risk.avg_r':               'Avg R',

    // ── Analyse Section Titles
    'an.title':                 'Analysis',
    'an.subtitle':              '{count} deep analytics — based on {trades} trades.',
    'an.empty':                 'No closed trades yet — this page comes alive once you have some.',
    'an.forecast':              'Equity Forecast',
    'an.forecast_subtitle':     'If your average from the last {range} continues.',
    'an.coach':                 'Coach mode — Weekly review',
    'an.coach_subtitle':        'Week starting {date} · vs. last week',
    'an.yearly':                'Trading year at a glance',
    'an.pareto':                'Pareto analysis: Who carries your account?',
    'an.whatif':                'What-if simulator',
    'an.holdtime':              'Hold time vs. result',
    'an.best_vs_worst':         'Best vs Worst — top 10 vs bottom 10',
    'an.streak':                'Streak statistics',
    'an.sequence':              'Sequential bias / revenge trading',
    'an.heatmap':               'Performance heatmap (day × hour)',
    'an.mfe_mae':               'MFE/MAE capture rate',
    'an.mistakes':              'Mistake cost analysis',
    'an.ulcer':                 'Ulcer index & recovery',
    'an.recovery':              'Recovery factor',
    'an.ror':                   'Risk-of-ruin & Kelly',
    'an.tag_matrix':            'Tag combo matrix',
    'an.vol_norm':              'Volatility-normalized returns',
    'an.consistency':           'Consistency score',
    'fc.basis':                 'Base',
    'fc.mode':                  'Mode',
    'fc.compound':              'Compound',
    'fc.linear':                'Linear',
    'fc.forecast':              'Forecast',
    'fc.target':                'Daily target',
    'fc.workday':               '/ weekday',
    'fc.disable_target':        'Disable daily target',
    'fc.avg_return_day':        'Avg return / day',
    'fc.avg_pnl_day':           'Avg P&L / day',
    'fc.current_equity':        'Current equity',
    'fc.in_x_days':             'In {days} days',
    'fc.expected_return':       'Expected return',
    'fc.x_trading_days':        '{count} trading days',
    'fc.vs_balance':            'vs. {label} ${value}',
    'fc.starting_capital':      'starting capital',
    'fc.mt5_equity':            'MT5 equity',
    'fc.if_pace_continues':     'If pace continues — goals',
    'fc.doubling':              'Doubling',
    'fc.plus_25':               '+25%',
    'fc.next_1k':               'Next $1k mark',
    'fc.reached':               '✓ reached',
    'fc.x_days':                '{days} days',
    'fc.x_years':                '{years} years',
    'fc.negative_pace':         'Current performance is negative — at this pace the account is melting. Switch to a larger base ({all}) for a more realistic picture, or fix the strategy first.',
    'fc.legend_actual':         'Actual equity',
    'fc.legend_forecast':       'Forecast (avg of last {range})',
    'fc.legend_target':         'Target ({pct}% / weekday, weekends flat)',
    'fc.confidence_band':       'Shaded area = ±1σ confidence band (~68% of paths inside).',
    'fc.compound_note':         'Compound mode: daily return is applied to the growing equity.',
    'fc.linear_note':           'Linear mode: fixed dollar amount per day, no reinvestment.',
    'fc.ahead_of_target':       '{pct}% above target',
    'fc.behind_target':         '{pct}% below target',
    'fc.target_explainer':      'At {pct}% per weekday you should be at ${target} now, but you are at ${current}. · Goal in {days} days: ${final}',
    'an.now':                   'Now',
    'an.start':                 'Start',
  },
}

function interpolate(template, vars) {
  if (!vars) return template
  return template.replace(/\{(\w+)\}/g, (_, key) => (vars[key] != null ? vars[key] : `{${key}}`))
}

/* ─── Provider ─────────────────────────────────────────────── */
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try { return localStorage.getItem(STORAGE_KEY) || 'de' } catch { return 'de' }
  })

  useEffect(() => {
    try { localStorage.setItem(STORAGE_KEY, language) } catch {}
    document.documentElement.lang = language
  }, [language])

  const t = useCallback((key, vars) => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.de
    const fallback = TRANSLATIONS.de
    const template = dict[key] ?? fallback[key] ?? key
    return interpolate(template, vars)
  }, [language])

  const toggle = useCallback(() => {
    setLanguage(prev => prev === 'de' ? 'en' : 'de')
  }, [])

  return (
    <Ctx.Provider value={{ language, setLanguage, toggle, t }}>
      {children}
    </Ctx.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(Ctx)
  if (!ctx) {
    // Safe fallback for the rare case the hook is called outside the provider
    return { language: 'de', setLanguage: () => {}, toggle: () => {}, t: (k) => k }
  }
  return ctx
}
