import { createContext, useContext, useState, useCallback, useEffect } from 'react'

const STORAGE_KEY = 'tradestats_language'
const Ctx = createContext(null)

/* ─── Translation dictionary ───────────────────────────────── */
const TRANSLATIONS = {
  de: {
    // ── App-wide
    'app.privacy':            'Privacy',
    'app.live_mt5_equity':    'Live MT5-Equity',
    'app.starting_capital':   'Anfangs-Kapital',
    'app.starting_capital.hint': 'Sobald MT5 verbunden ist, wird automatisch die Live-Equity übernommen.',
    'app.starting_capital.live_hint': 'ROI-Basis wird automatisch von deinem MT5-Account übernommen — keine manuelle Eingabe nötig.',
    'app.ok':                 'OK',

    // ── Sidebar
    'nav.dashboard':       'Dashboard',
    'nav.journal':         'Trade Journal',
    'nav.daily_journal':   'Daily Journal',
    'nav.calendar':        'Kalender',
    'nav.analyse':         'Analyse',
    'nav.setups':          'Setups',
    'nav.risk':            'Risiko',
    'nav.profile':         'Profil',
    'nav.import':          'Import',
    'nav.export':          'Export',
    'nav.live':            'Live',
    'nav.offline':         'Offline',
    'nav.mt5_disconnected': 'MT5 getrennt',
    'nav.trading_journal': 'Trading Journal',

    // ── Common
    'common.save':         'Speichern',
    'common.saved':        'Gespeichert',
    'common.cancel':       'Abbrechen',
    'common.delete':       'Löschen',
    'common.confirm':      'Bestätigen',
    'common.confirm_q':    'Wirklich löschen?',
    'common.back':         'Zurück',
    'common.close':        'Schließen',
    'common.search':       'Suchen',
    'common.filter':       'Filter',
    'common.reset':        'Zurücksetzen',
    'common.add':          'Hinzufügen',
    'common.edit':         'Bearbeiten',
    'common.copy':         'Kopieren',
    'common.copied':       'Kopiert!',
    'common.download':     'Download',
    'common.upload':       'Hochladen',
    'common.all':          'Alle',
    'common.none':         'Keine',
    'common.from':         'Von',
    'common.to':           'Bis',
    'common.symbol':       'Symbol',
    'common.type':         'Typ',
    'common.volume':       'Volumen',
    'common.volume_short': 'Vol.',
    'common.price':        'Preis',
    'common.entry':        'Entry',
    'common.exit':         'Exit',
    'common.open':         'Open',
    'common.current':      'Aktuell',
    'common.duration':     'Dauer',
    'common.pnl':          'P&L',
    'common.profit':       'Gewinn',
    'common.loss':         'Verlust',
    'common.trades':       'Trades',
    'common.trade':        'Trade',
    'common.win_rate':     'Win Rate',
    'common.profit_factor':'Profit Faktor',
    'common.notes':        'Notizen',
    'common.tags':         'Tags',
    'common.tag':          'Tag',
    'common.date':         'Datum',
    'common.day':          'Tag',
    'common.week':         'Woche',
    'common.month':        'Monat',
    'common.year':         'Jahr',
    'common.all_time':     'Alles',
    'common.today':        'Heute',
    'common.yesterday':    'Gestern',
    'common.this_week':    'Diese Woche',
    'common.last_week':    'Letzte Woche',
    'common.this_month':   'Dieser Monat',
    'common.last_month':   'Letzter Monat',
    'common.this_year':    'Dieses Jahr',
    'common.last_year':    'Letztes Jahr',
    'common.all_times':    'Alle Zeiten',
    'common.generated_at': 'Generiert am',
    'common.last_update':  'Letztes Update',
    'common.never':        'Nie',
    'common.no_trades':    'Keine Trades vorhanden',
    'common.no_trades_found': 'Keine Trades gefunden',
    'common.no_data':      'Keine Daten',
    'common.loading':      'Lade...',
    'common.failed':       'Fehlgeschlagen',
    'common.success':      'Erfolgreich',
    'common.preview':      'Vorschau',
    'common.timeframe':    'Zeitraum',
    'common.trading_days': 'Trading-Tage',
    'common.connected':    'verbunden',
    'common.not_connected':'nicht verbunden',
    'common.position':     'Position',
    'common.positions':    'Positionen',

    // ── Trade Journal
    'journal.title':          'Trade Journal',
    'journal.add_trade':      'Trade hinzufügen',
    'journal.sync':           'Sync',
    'journal.syncing':        'Synchronisiere…',
    'journal.search_placeholder': 'Suche nach Symbol, Notiz, Tag...',
    'journal.more_filters':   'Mehr Filter',
    'journal.groups_detected':'erkannt',
    'journal.x_of_y_filtered':'{shown} von {total} Trades gefiltert',
    'journal.selected':       '{count} ausgewählt',
    'journal.deselect':       'Aufheben',
    'journal.bulk_delete':    'Löschen',
    'journal.delete_trade':   'Trade löschen',
    'journal.delete_confirm': 'Trade wirklich löschen?',
    'journal.trade_deleted':  'Trade gelöscht',
    'journal.trades_deleted': '{count} Trades gelöscht',
    'journal.undo':           'Rückgängig',
    'journal.undo_hint':      'Klick auf Rückgängig zum Wiederherstellen',
    'journal.dissolve_group': 'Gruppe auflösen',
    'journal.remove_from_group': 'Aus Gruppe entfernen',
    'journal.no_autogroup':   'Nicht auto-gruppieren',
    'journal.enable_autogroup': 'Auto-Group aktivieren',
    'journal.drag_hint':      'Trades per Drag & Drop manuell gruppieren — einfach eine Zeile auf eine andere ziehen.',
    'journal.col_avg_entry':  'Ø Entry',
    'journal.col_avg_exit':   'Ø Exit',
    'journal.symbol_choose':  'Symbol wählen',
    'journal.cat_all':         'Alle',
    'journal.cat_forex':       'Forex',
    'journal.cat_commodities': 'Commodities',
    'journal.cat_indices':     'Indices',
    'journal.cat_crypto':      'Crypto',
    'journal.cat_stocks':      'Aktien',
    'journal.tag_all':         'Alle Tags',
    'journal.sync_done':       'Sync erfolgreich',
    'journal.sync_failed':     'Synchronisierung fehlgeschlagen',
    'journal.sync_already_up_to_date': 'Bereits aktuell',
    'journal.sync_updated':    '{count} aktualisiert',
    'journal.sync_new':        '{count} neu',
    'journal.sync_x_from_mt5': '{parts} aus MT5',
    'journal.sync_x_in_backend': '{count} Trades im Backend, alle synchron',
    'journal.manual':         'manuell',
    'journal.select_all':     'Alle auswählen',
    'journal.groups':         'Gruppen',

    // ── Trade Detail Modal
    'modal.opened':          'Geöffnet',
    'modal.closed':          'Geschlossen',
    'modal.new_tag':         'Neuer Tag...',
    'modal.mark_mistakes':   'Fehler markieren (optional, ehrlich sein zahlt sich aus)',
    'modal.mistakes_hint':   'Diese Markierungen fließen in die Fehler-Kosten-Analyse auf der Analyse-Seite ein.',
    'modal.notes_placeholder': 'Trade-Analyse, Emotionen, Verbesserungen...',
    'modal.setup_label':     'Setup',
    'modal.no_setup':        '— Kein Setup zugeordnet —',
    'modal.setup_target_rr': 'Ziel R:R',
    'modal.opening':         'Eröffnung',
    'modal.closing':         'Schluss',
    'modal.lot':             'Lot',
    'modal.stop_loss':       'Stop Loss',
    'modal.take_profit':     'Take Profit',
    'modal.commission':      'Kommission',
    'modal.swap':            'Swap',
    'modal.gross_profit':    'Rohgewinn',
    'modal.net_pnl':         'Netto P&L',

    // ── Add Trade Modal
    'add.title':             'Trade hinzufügen',
    'add.commission':        'Kommission',
    'add.swap':              'Swap',
    'add.add_trade':         'Trade hinzufügen',

    // ── Live Sync Panel
    'live.open_positions':   'Offene Positionen',
    'live.groups':           '{count} Gruppe',
    'live.groups_plural':    '{count} Gruppen',
    'live.no_positions':     'Keine offenen Positionen',
    'live.mt5_connected':    'TMGM MT5 verbunden',
    'live.mt5_not_connected':'MT5 nicht verbunden',
    'live.connection_info':  '{trade_count} Trades · {pos_count} Position',
    'live.col_risk_reward':  'Risk/Reward',
    'live.position_note':    'Position-Notiz',
    'live.note_placeholder': 'Warum bin ich eingestiegen? Setup, Bias, Levels...',
    'live.add_tag':          'Tag hinzufügen...',
    'live.account':          'Account',
    'live.balance':          'Balance',
    'live.equity':           'Equity',
    'live.open_pnl':         'Offener P&L',
    'live.margin_level':     'Margin Level',
    'live.x_imported':       '{count} Trade importiert',
    'live.x_imported_plural':'{count} Trades importiert',
    'live.auto_imported':    'Automatisch aus MT5 synchronisiert',

    // ── Setup Library
    'setups.title':            'Setup-Bibliothek',
    'setups.subtitle':         'Deine Trading-Playbooks',
    'setups.setups_defined':   '{count} Setup definiert',
    'setups.setups_defined_plural': '{count} Setups definiert',
    'setups.unassigned':       '{count} Trades noch nicht zugeordnet',
    'setups.new_setup':        'Neues Setup',
    'setups.edit_setup':       'Setup bearbeiten',
    'setups.no_setups':        'Noch keine Setups definiert',
    'setups.no_setups_hint':   'Lege deine Trading-Setups als wiederverwendbare Playbooks an. Jeder Trade kann später einem Setup zugeordnet werden, damit du siehst, welche deiner Strategien wirklich Geld bringen.',
    'setups.field_name':       'Name',
    'setups.field_color':      'Farbe',
    'setups.field_description':'Beschreibung',
    'setups.desc_placeholder': 'In welcher Marktphase setzt du das? Was ist die These?',
    'setups.field_target_rr':  'Ziel R:R',
    'setups.field_max_risk':   'Max Risiko %',
    'setups.entry_rules':      'Entry-Regeln',
    'setups.exit_rules':       'Exit-Regeln',
    'setups.entry_placeholder':'z.B. Preis über Tages-VWAP',
    'setups.exit_placeholder': 'z.B. SL unter letztem Tief',
    'setups.add_rule':         'Regel hinzufügen',
    'setups.create':           'Setup anlegen',
    'setups.delete_confirm':   'Setup "{name}" wirklich löschen?',
    'setups.entry_section':    'Entry:',
    'setups.exit_section':     'Exit:',
    'setups.more_rules':       '… +{count} mehr',
    'setups.risk':             'Risiko',

    // ── Profile / Share
    'profile.title':            'Profil',
    'profile.subtitle':         'Teile deine Trading-Performance — ohne absolute Dollarbeträge',
    'profile.share_export':     'Teilen & Exportieren',
    'profile.copy_image':       'Bild in Zwischenablage',
    'profile.image_copied':     'Bild kopiert!',
    'profile.creating_image':   'Erstelle Bild…',
    'profile.copy_image_hint':  'PNG direkt in Zwischenablage — perfekt zum Posten',
    'profile.paste_hint':       'Mit Ctrl+V in Discord, Telegram etc. einfügen',
    'profile.download_png':     'PNG herunterladen',
    'profile.download_png_hint':'Speichert die Share-Card als hochauflösendes Bild',
    'profile.copy_link':        'Link kopieren',
    'profile.link_copied':      'Link kopiert!',
    'profile.copy_link_hint':   'URL mit Base64-codierten Stats — Read-Only-Ansicht',
    'profile.export_pdf':       'PDF exportieren',
    'profile.export_pdf_hint':  'Druckt nur die Share-Card, ohne Navigation',
    'profile.share_safe_hint':  'Bild, PDF & Link enthalten keine absoluten Dollarbeträge.',
    'profile.no_dollar':        'Keine absoluten Dollarbeträge',
    'profile.included_metrics': 'Enthaltene Metriken',
    'profile.no_trades_in_period':'Keine Trades in diesem Zeitraum',
    'profile.review_day':       'Tagesrückblick',
    'profile.review_week':      'Wochenrückblick',
    'profile.review_month':     'Monatsrückblick',
    'profile.review_year':      'Jahresrückblick',
    'profile.review_all':       'Gesamt-Performance',
    'profile.best_trade':       'Bester Trade',
    'profile.top_n_trades':     'Top {count} Trade',
    'profile.top_n_trades_plural':'Top {count} Trades',
    'profile.avg_trades_day':   'Ø Trades/Tag',
    'profile.go_to_today':      'Zurück zur aktuellen Periode',
    'profile.prev_day':         'Vorheriger Tag',
    'profile.prev_week':        'Vorherige Woche',
    'profile.prev_month':       'Vorheriger Monat',
    'profile.prev_year':        'Vorheriges Jahr',
    'profile.next_period':      'Nächste Periode',
    'profile.future':           'Zukunft',
    // Mentor brief
    'mb.title':                 'Mentor-Brief',
    'mb.subtitle':              'Strukturierte Performance-Zusammenfassung zum Teilen mit Coach/AI-Mentor.',
    'mb.privacy_mode':          'Privacy-Modus',
    'mb.privacy_full':          'Voll',
    'mb.privacy_full_desc':     '$ Beträge',
    'mb.privacy_relative':      'R-Multiples',
    'mb.privacy_relative_desc': 'Risiko-relativ',
    'mb.privacy_anonymous':     'Anonym',
    'mb.privacy_anonymous_desc':'Nur Ratios',
    'mb.share_notes':           'Notizen mit teilen',
    'mb.focus_label':           'Fokus für die Session (optional)',
    'mb.focus_placeholder':     "Worüber willst du reden? z.B. 'Warum überhandle ich nach Lossern? Welches Setup soll ich streichen?'",
    'mb.generate':              'Brief generieren',
    'mb.copy_md':               'Markdown kopieren',
    'mb.copy_md_done':          'Kopiert!',
    'mb.show_preview':          'Vorschau anzeigen',
    // Backup
    'backup.title':             'Backup & Wiederherstellung',
    'backup.subtitle':          'Alle Trades, Tags, Gruppen & Notizen liegen lokal im Browser — JSON-Export schützt vor Datenverlust.',
    'backup.export':            'Backup exportieren (JSON)',
    'backup.export_hint':       '{trades} Trades, {notes} Position-Notizen',
    'backup.restore':           'Backup wiederherstellen',
    'backup.restore_hint':      'Überschreibt aktuelle Trades, Tags und Notizen',
    'backup.restore_confirm':   'Backup wiederherstellen?',
    'backup.restore_file':      'Datei',
    'backup.restore_exported':  'Exportiert',
    'backup.restore_trades_in_backup': 'Trades im Backup',
    'backup.restore_warning':   'Achtung: Aktuelle Trades, Tags, Gruppen und Notizen werden komplett überschrieben. Sicher dass du fortfahren willst?',
    'backup.restore_action':    'Wiederherstellen',

    // ── Dashboard / Analyse common
    'dash.equity_curve':        'Equity Kurve',
    'dash.monthly_pnl':         'Monatlicher P&L',
    'dash.drawdown':            'Drawdown',
    'dash.hold_duration':       'Ø Haltedauer nach Symbol',
    'dash.pnl_by_symbol':       'P&L nach Symbol',
    'dash.total_pnl':           'Gesamt P&L',
    'dash.roi':                 'ROI',
    'dash.avg_rr':              'Ø R:R',
    'dash.basis':               'Basis',
    'dash.winners':             '{count} Gewinner',
    'dash.choose_timeframe':    'Zeitraum auswählen',
    'dash.apply':               'Anwenden',
    'dash.choose_date':         'Eigenen Zeitraum wählen',
    'dash.date_short':          'Datum',
    'dash.tf_1d':               '1T',
    'dash.tf_1w':               '1W',
    'dash.tf_1m':               '1M',
    'dash.tf_3m':               '3M',
    'dash.tf_6m':               '6M',
    'dash.tf_1y':               '1J',
    'dash.tf_all':              'Alles',
    'dash.x_of_y_filtered':     '{shown} von {total} Trades gefiltert',
    'dash.x_trades_pos_grouped':'({positions} Positionen, {groups} gruppiert)',
    'dash.excellent':           'Exzellent',
    'dash.good':                'Gut',
    'dash.bad':                 'Schlecht',
    'dash.improve':             'Verbesserung',
    'dash.basis_label':         'Basis',
    'dash.win_rate':            'Win Rate',
    'dash.trades_label':        'Trades',
    'dash.symbol_col':          'Symbol',
    'dash.winners_col':         'Gewinner',
    'dash.pnl':                 'P&L',

    // ── Risk
    'risk.title':               'Risiko-Analyse',
    'risk.based_on':            'Basierend auf {pct}% Risiko pro Trade',
    'risk.avg_risk':            'Ø Risiko pro Trade',
    'risk.max_risk':            'Max. Risiko pro Trade',
    'risk.fixed_model':         'Fixiertes Risiko-Modell',
    'risk.avg_r_multiple':      'Ø R-Multiple',
    'risk.expectancy_positive': 'Profitabler Erwartungswert',
    'risk.expectancy_negative': 'Erwartungswert negativ',
    'risk.r_distribution':      'R-Multiple Verteilung',
    'risk.all_trades':          'Alle Trades',
    'risk.tilt_detector':       'Tilt-Detektor',
    'risk.tilt_subtitle':       'Verhalten nach Verlust-Serien',
    'risk.tilt_need_data':      'Mindestens 5 Trades nach Gewinn-Phasen nötig, um eine Baseline zu berechnen — aktuell {count}.',
    'risk.tilt_normal':         'Normalzustand',
    'risk.tilt_normal_desc':    'Nach Gewinn / Start',
    'risk.tilt_one_loss':       '1 Loser davor',
    'risk.tilt_first_loss':     'Erste Niederlage',
    'risk.tilt_two_losses':     '2 Loser davor',
    'risk.tilt_frustzone':      'Frust zone',
    'risk.tilt_three_plus':     '3+ Loser davor',
    'risk.tilt_zone':           'Tilt-Bereich',
    'risk.tilt_too_little_data':'Zu wenig Daten',
    'risk.tilt_no_pattern':     'Kein Tilt-Muster erkennbar — du behältst die Disziplin nach Verlust-Serien. Stark.',
    'risk.avg_volume':          'Ø Volumen',
    'risk.avg_pnl':             'Ø P&L',
    'risk.avg_r':               'Ø R',

    // ── Analyse Section Titles
    'an.title':                 'Analyse',
    'an.subtitle':              '{count} tiefe Auswertungen — basierend auf {trades} Trades.',
    'an.empty':                 'Noch keine abgeschlossenen Trades — sobald welche da sind, lebt diese Seite auf.',
    'an.forecast':              'Equity-Prognose',
    'an.forecast_subtitle':     'Wenn dein Schnitt der letzten {range} so weiterläuft.',
    'an.coach':                 'Coach-Mode — Wochenrückblick',
    'an.coach_subtitle':        'Woche ab {date} · vs. Vorwoche',
    'an.yearly':                'Trading-Jahr auf einen Blick',
    'an.pareto':                'Pareto-Analyse: Wer trägt deinen Account?',
    'an.whatif':                'Was-wäre-wenn-Simulator',
    'an.holdtime':              'Hold-Time vs. Ergebnis',
    'an.best_vs_worst':         'Best vs Worst — die 10 Besten gegen die 10 Schlechtesten',
    'an.streak':                'Streak-Statistik',
    'an.sequence':              'Sequenz-Bias / Revenge-Trading',
    'an.heatmap':               'Performance-Heatmap (Tag × Stunde)',
    'an.mfe_mae':               'MFE/MAE-Capture-Rate',
    'an.mistakes':              'Fehler-Kosten-Analyse',
    'an.ulcer':                 'Ulcer-Index & Recovery',
    'an.recovery':              'Recovery Factor',
    'an.ror':                   'Risk-of-Ruin & Kelly-Fraction',
    'an.tag_matrix':            'Tag-Kombi-Matrix',
    'an.vol_norm':              'Volatilitäts-normalisierte Returns',
    'an.consistency':           'Konsistenz-Score',
    // Forecast controls
    'fc.basis':                 'Basis',
    'fc.mode':                  'Modus',
    'fc.compound':              'Zinseszins',
    'fc.linear':                'Linear',
    'fc.forecast':              'Prognose',
    'fc.target':                'Tagesziel',
    'fc.workday':               '/ Werktag',
    'fc.disable_target':        'Tagesziel deaktivieren',
    'fc.avg_return_day':        'Ø Rendite / Tag',
    'fc.avg_pnl_day':           'Ø P&L / Tag',
    'fc.current_equity':        'Aktuelle Equity',
    'fc.in_x_days':             'In {days} Tagen',
    'fc.expected_return':       'Erwartete Rendite',
    'fc.x_trading_days':        '{count} Trading-Tage',
    'fc.vs_balance':            'vs. {label} ${value}',
    'fc.starting_capital':      'Startkapital',
    'fc.mt5_equity':            'MT5-Equity',
    'fc.if_pace_continues':     'Wenn das Tempo so bleibt — Ziele',
    'fc.doubling':              'Verdopplung',
    'fc.plus_25':               '+25%',
    'fc.next_1k':               'Nächste $1k-Marke',
    'fc.reached':               '✓ erreicht',
    'fc.x_days':                '{days} Tage',
    'fc.x_years':                '{years} Jahre',
    'fc.negative_pace':         'Aktuelle Performance ist negativ — bei diesem Tempo schmilzt der Account. Wechsel zur größeren Basis ({all}) für ein realistischeres Bild oder fix erst die Strategie.',
    'fc.legend_actual':         'Tatsächliche Equity',
    'fc.legend_forecast':       'Prognose (Schnitt der letzten {range})',
    'fc.legend_target':         'Ziel ({pct}% / Werktag, Wochenenden flach)',
    'fc.confidence_band':       'Schattierter Bereich = ±1σ Vertrauensband (~68% der Pfade liegen drin).',
    'fc.compound_note':         'Zinseszins-Modus: tägliche Rendite wird auf das wachsende Equity angewendet.',
    'fc.linear_note':           'Linear-Modus: fester Dollar-Betrag pro Tag, kein Reinvestment.',
    'fc.ahead_of_target':       '{pct}% über Ziel',
    'fc.behind_target':         '{pct}% hinter Ziel',
    'fc.target_explainer':      'Bei {pct}% pro Werktag müsstest du jetzt bei ${target} stehen, bist aber bei ${current}. · Ziel in {days} Tagen: ${final}',

    // Other Analyse sub-strings & badges
    'an.now':                   'Jetzt',
    'an.start':                 'Start',

    // ── Setup-Wizard ───────────────────────────────────────────
    'setup.welcome':            'Willkommen bei TradeStats',
    'setup.welcome_subtitle':   'Damit diese Web-App deine MT5-Trades sehen kann, brauchst du einmalig den TradeStats-Connector auf deinem PC. Das dauert ~2 Minuten.',
    'setup.banner.offline.title':       'Connector noch nicht gestartet',
    'setup.banner.offline.body':        'TradeStats-Connector unter {url} nicht erreichbar.',
    'setup.banner.backend_only.title':  'Connector läuft — MT5 fehlt',
    'setup.banner.backend_only.body':   'MetaTrader 5 ist nicht verbunden. Bitte MT5 öffnen und einloggen.',
    'setup.banner.checking.title':      'Prüfe Verbindung...',
    'setup.checking':                   'Verbinde mit TradeStats-Connector...',
    'setup.step1.title':                'Connector herunterladen',
    'setup.step1.body':                 'Lade den TradeStats-Connector herunter — ein kleines Programm, das deine MT5-Daten an diese Web-App liefert.',
    'setup.step1.action':               'Connector herunterladen',
    'setup.step2.title':                'Installer ausführen',
    'setup.step2.body':                 'Doppelklick auf TradeStats_Setup.exe. Folge dem Setup-Assistenten — keine besonderen Optionen nötig. Dauert ca. 30 Sek.',
    'setup.step3.title':                'MetaTrader 5 öffnen',
    'setup.step3.body':                 'Starte deinen MT5-Terminal und logge dich in dein Konto ein. Der Connector spricht über die MT5-Python-API und braucht ein aktives Terminal-Login.',
    'setup.step3.hint':                 'Demo-Account funktioniert genauso wie ein Live-Account.',
    'setup.step4.title':                'Connector starten',
    'setup.step4.body':                 'Starte den TradeStats-Connector (Desktop-Verknüpfung oder Startmenü). Ein Konsolen-Fenster öffnet sich und bleibt offen. Dieses Fenster nicht schließen — solange du tradest.',
    'setup.step4.body_done':            'Connector läuft ✓ — wir warten nur noch auf die MT5-Verbindung.',
    'setup.step4.hint':                 'Falls Windows-Firewall fragt: "Zugriff zulassen" — der Connector hört nur auf localhost (127.0.0.1).',
    'setup.success.title':              'Connector verbunden!',
    'setup.success.body':               'Lade jetzt deine Trades... du wirst gleich umgeleitet.',
    'setup.waiting_hint':               'Ich prüfe alle 3 Sekunden, ob der Connector erreichbar ist. Sobald er läuft, geht’s automatisch weiter — du brauchst hier nichts zu klicken.',
    'setup.about_connector':            'Was ist der Connector?',
    'setup.skip_csv':                   'Ohne Connector weitermachen (CSV-Import)',
    'setup.badge.offline':              'Connector offline',
    'setup.badge.mt5_off':              'MT5 nicht verbunden',
    'setup.badge.show_tooltip':         'Setup-Anleitung wieder anzeigen',
    'setup.trades_count':               '{count} Trade{plural}',
    // SmartScreen-Hinweis
    'setup.ss.toggle':                  'Windows zeigt eine Warnung? Das ist normal — so klickst du sie weg',
    'setup.ss.explain':                 'Beim ersten Start blockiert {dfdr} den Installer, weil er nicht von Microsoft signiert ist. Code-Signing-Zertifikate kosten 300+ €/Jahr — für ein Hobbyprojekt unverhältnismäßig. Der Code ist {github}, du kannst dich also selbst überzeugen, dass nichts Bösartiges drin ist.',
    'setup.ss.defender':                'Windows Defender SmartScreen',
    'setup.ss.github_open':             'offen einsehbar auf GitHub',
    'setup.ss.protected_title':         'Der Computer wurde durch Windows geschützt',
    'setup.ss.body1':                   'Von Microsoft Defender SmartScreen wurde der Start einer unbekannten App verhindert.',
    'setup.ss.more_info':               'Weitere Informationen',
    'setup.ss.click_1':                 '← 1. Klick hier',
    'setup.ss.click_2':                 '2. Klick hier →',
    'setup.ss.dont_run':                'Nicht ausführen',
    'setup.ss.run_anyway':              'Trotzdem ausführen',
    'setup.ss.between':                 'Danach erscheint ein neuer Button:',
    'setup.ss.app_label':               'App:',
    'setup.ss.footer':                  'Sobald du einmal „Trotzdem ausführen" geklickt hast, merkt sich Windows die Entscheidung — beim nächsten Start kommt die Warnung nicht mehr.',

    // ── Hold-Duration-Trend Card ───────────────────────────────
    'hd.title':                 'Ø Haltedauer pro Tag',
    'hd.subtitle':              '{days} Trading-Tage · Schnitt insgesamt: {avg}',
    'hd.empty_subtitle':        'Keine Trades im gewählten Zeitraum',
    'hd.empty_hint':            'Wähle einen anderen Zeitraum.',
    'hd.info':                  'Durchschnittliche Haltedauer aller Trades pro Trading-Tag, plus 7-Tage-Rolling-Average (geglättete Linie) zur Trend-Erkennung. Hilft zu sehen, ob du im Laufe der Zeit deine Trades länger laufen lässt (mehr Geduld) oder immer schneller raus gehst (Angst/Ungeduld) — beides ist verhaltens-relevant für deine Edge.',
    'hd.range_label':           'Zeitraum:',
    'hd.range.month':           'Monat',
    'hd.range.year':            'Jahr',
    'hd.range.all':             'Gesamt',
    'hd.trades_count':          '{n} Trades',
    'hd.first_half':            'Erste Hälfte',
    'hd.second_half':           'Zweite Hälfte',
    'hd.trend.up':              'Haltedauer ist um {pct}% gestiegen — du hältst länger als früher.',
    'hd.trend.down':            'Haltedauer ist um {pct}% gesunken — du gehst schneller raus.',
    'hd.trend.stable':          'Haltedauer ist konstant geblieben (±{pct}%).',
    'hd.legend':                'Türkise Balken = Tages-Durchschnitt · Orange Linie = 7-Tage-Rolling-Average (geglättet) · Graue Linie = Gesamt-Schnitt aller Trades.',
    'hd.tooltip.day':           'Tag-Ø: {value}',
    'hd.tooltip.rolling':       '7-Tage-Ø: {value}',

    // ── Sizing-Konsistenz ──────────────────────────────────────
    'sc.title':                 'Sizing-Konsistenz',
    'sc.subtitle':              'Ø Position: {avg} Lot · maximale Abweichung: {dev}%',
    'sc.info':                  'Vergleicht deine durchschnittliche Position-Größe (Lot-Volumen) je nach Vor-Trade-Situation. Statistisch dürftest du immer gleich viel riskieren — wenn du nach Verlusten plötzlich größer oder kleiner sizierst, ist das emotionsgetrieben und untergräbt deine Edge. Größter Hebel: Sizing-Drift erklärt oft die schmerzhaftesten Drawdowns.',
    'sc.bucket.opening':        'Eröffnungs-Trade',
    'sc.bucket.afterWin':       'Nach Gewinn',
    'sc.bucket.afterLoss':      'Nach Verlust',
    'sc.bucket.after2Loss':     'Nach 2+ Verlusten',
    'sc.bucket.afterBigLoss':   'Nach großem Verlust',
    'sc.verdict.bad.title':     'Stark inkonsistent',
    'sc.verdict.bad.body':      'Bis zu {dev}% Abweichung — du sizierst je nach Stimmung deutlich anders. Klassisches Tilt-/Übermut-Symptom.',
    'sc.verdict.warn.title':    'Leicht inkonsistent',
    'sc.verdict.warn.body':     '{dev}% Abweichung. Noch okay, aber im Auge behalten — Sizing sollte aus dem Plan kommen, nicht aus dem letzten Trade.',
    'sc.verdict.good.title':    'Konsistent',
    'sc.verdict.good.body':     'Nur {dev}% Abweichung zwischen den Buckets. Du sizierst diszipliniert unabhängig von Vorgängern.',
    'sc.trades_count':          '{n} Trade{plural}',
    'sc.lot_unit':              '{n} Lot',
    'sc.wr':                    'WR',
    'sc.legend':                'Senkrechter Strich = Durchschnitt aller Trades. Balken-Position zeigt Abweichung. Rot ab ±25%, Gelb ab ±10%.',

    // ── Konkurrierende Positionen ──────────────────────────────
    'cp.title':                 'Konkurrierende Positionen',
    'cp.subtitle':              'Ø {avg} parallel offen · max. {max} · {solo}% Solo-Trades',
    'cp.info':                  'Misst, wie viele andere Positionen typischerweise gleichzeitig offen sind, wenn du einen neuen Trade öffnest. Wenn du 3 USD-Pairs gleichzeitig long bist, hast du eigentlich einen einzigen „Dollar-Schwäche“-Trade mit 3× Risiko. Die Symbol-Paare unten zeigen, welche Kombinationen am häufigsten gleichzeitig laufen — Korrelations-Check empfohlen.',
    'cp.verdict.good.title':    'Sauber sequenziell',
    'cp.verdict.good.body':     'Im Schnitt nur {avg} weitere Position offen. {solo}% deiner Trades sind solo — sauberes, fokussiertes Trading ohne Cluster-Risiko.',
    'cp.verdict.warn.title':    'Moderate Überschneidung',
    'cp.verdict.warn.body':     'Ø {avg} weitere Positionen offen, max. {max}. Achte darauf, ob die Symbole korreliert sind — sonst multiplizierst du dein Risiko unbemerkt.',
    'cp.verdict.bad.title':     'Hohe Konzentration',
    'cp.verdict.bad.body':      'Ø {avg} weitere Positionen — du hältst oft viel gleichzeitig. Wenn die Symbole korrelieren, hast du de facto 1 Trade mit {max}× Risiko. Sehr unterschätzte Drawdown-Quelle.',
    'cp.top_pairs':             'Häufigste Symbol-Paare (gleichzeitig offen)',
    'cp.overlap_times':         '{count}× überlappt',
    'cp.overlap_hours':         '{hours}h gemeinsam',
    'cp.no_overlap':            'Keine zeitlich überlappenden Trades — du tradest streng sequenziell.',
    'cp.tip':                   'Tipp: Prüfe bei Top-Paaren die Korrelation (z.B. EURUSD/GBPUSD = ~0.85). Hohe positive Korrelation = effektive Risiko-Verdopplung.',

    // ── Trading-Frequenz-Trend ─────────────────────────────────
    'tf.title':                 'Trading-Frequenz-Trend',
    'tf.subtitle':              'Ø {avg} Trades pro Tag · {days} Trading-Tage',
    'tf.info':                  'Anzahl Trades pro Tag mit 7-Tage-Rolling-Average und gleichzeitiger Win-Rate. Klassisches Overtrading-Muster: Frequenz steigt + Win-Rate fällt → du gönnst dir nicht mehr nur die A-Setups, sondern hängst auch B- und C-Setups dran. Frühindikator für Tilt oder Boredom-Trading.',
    'tf.verdict.overtrading.title': 'Overtrading-Warnung',
    'tf.verdict.overtrading.body':  'Deine Trade-Frequenz ist um {freq}% gestiegen, gleichzeitig fiel die Win-Rate um {wr} Punkte. Klassisches Muster: mehr Trades, schlechtere Qualität.',
    'tf.verdict.rising.title':  'Frequenz steigt',
    'tf.verdict.rising.body':   '{freq}% mehr Trades pro Tag — Win-Rate hält noch ({wr_sign}{wr} Pt). Wachsam bleiben, dass Quantität nicht Qualität ersetzt.',
    'tf.verdict.falling.title': 'Frequenz sinkt',
    'tf.verdict.falling.body':  '{freq}% weniger Trades. Selektiver geworden oder Phase mit weniger Setups — Win-Rate-Veränderung: {wr_sign}{wr} Pt.',
    'tf.verdict.stable.title':  'Stabile Frequenz',
    'tf.verdict.stable.body':   'Trade-Anzahl konstant (±{freq}%). Solide Routine — Disziplin ist sichtbar.',
    'tf.first_half':            'Erste Hälfte',
    'tf.second_half':           'Zweite Hälfte',
    'tf.trades_per_day':        'Trades/Tag',
    'tf.legend':                'Orange = Trades/Tag (Balken + 7-Tage-Linie) · Blau gestrichelt = 7-Tage-Win-Rate (rechte Achse). Wenn Orange steigt UND Blau fällt: Overtrading-Verdacht.',

    // ── AI-Coach ──────────────────────────────────────────────
    'coach.title':              'AI-Coach',
    'coach.subtitle':           '{count} Insights · {good} stark · {bad} kritisch · {tip} Hinweise',
    'coach.info':               'Automatisch generierte Einschätzung deiner Performance über alle Metriken: was läuft gut, wo lauert Risiko, wo gibt es konkrete Verbesserungs-Hebel. Schwellwerte basieren auf etablierten Trading-Statistik-Standards (Profit-Faktor, R-Ratio, Recovery Factor, Risk of Ruin). Keine Glaskugel — datengetriebene Hypothesen, die du in deinem nächsten Trade-Plan prüfen kannst.',
    'coach.no_data':            'Zu wenige Trades für eine fundierte Einschätzung — mindestens 10 abgeschlossene Trades helfen.',
    'coach.core_points':        'Kernpunkte',
    'coach.severity.good':      'Stark',
    'coach.severity.warn':      'Achtung',
    'coach.severity.bad':       'Risiko',
    'coach.severity.tip':       'Hinweis',
    'coach.intro':              'Ich habe deine {count} abgeschlossenen Trades durch alle Analyse-Module geschickt. Hier mein Eindruck:',
    'coach.positive_lead':      '**Was du richtig machst:**',
    'coach.positive_close.single': 'Insgesamt ein klarer Lichtblick — bleib bei diesen Mustern ({headlines}).',
    'coach.positive_close.multi':  'Insgesamt {n} Lichtblicke — bleib bei diesen Mustern ({headlines}).',
    'coach.positive_none':      '**Was du richtig machst:** Auf den großen Kennzahlen ragt aktuell nichts heraus — das ist kein Drama, aber auch kein Polster. Konzentriere dich darauf, mindestens eine Stärke auszubauen, bevor du an mehreren Hebeln gleichzeitig schraubst.',
    'coach.critical_lead':      '**Was dich aktuell Geld kostet:**',
    'coach.critical_close':     'Wenn du diese Woche an einer Sache arbeiten würdest, dann an der ersten Position oben — dort steckt der größte Hebel.',
    'coach.critical_none':      '**Was dich aktuell Geld kostet:** Keine roten Flaggen auf den Hauptmetriken. Achtung: das ist eine Momentaufnahme — kleine Stichproben können Risiken kaschieren. Bleib bei striktem Risk-Management.',
    'coach.outlook_lead':       '**Zum Weiterdenken:**',

    // ── MAE-Risk + Margin-Exposure (Risk Tab) ─────────────────
    'rt.mae.title':             'Realisiertes Risiko (MAE)',
    'rt.mae.empty':              'Noch zu wenig MFE/MAE-Daten',
    'rt.mae.empty_body':        'MFE/MAE-Tracking läuft im Hintergrund über das Live-Sync. Sobald genug Trades archiviert sind ({count} bisher), erscheint hier dein realisiertes Risiko-Profil.',
    'rt.mae.subtitle':          '{count} Trades mit MFE/MAE',
    'rt.mae.info':              'Maximum Adverse Excursion: wie tief ein Trade tatsächlich im Drawdown war, bevor er geschlossen wurde. Für Trader ohne festen SL der ehrlichste Risiko-Indikator.',
    'rt.mae.verdict.bad.title': 'Hohes realisiertes Risiko',
    'rt.mae.verdict.bad.body':  '95% deiner Trades blieben unter {p95}% Drawdown — aber das heißt auch: 5% gingen tiefer. Bei deinem Konto sind das ~${abs} Schmerz pro Trade. Ohne SL ist der Tail-Worst-Case dein eigentliches Risiko.',
    'rt.mae.verdict.warn.title': 'Moderates Risiko',
    'rt.mae.verdict.warn.body':  '95-Perzentil-MAE liegt bei {p95}% des Kontos. Vertretbar, aber im Auge behalten — dort steckt dein "in 1 von 20 Trades"-Worst-Case.',
    'rt.mae.verdict.good.title': 'Kontrollierte Drawdowns',
    'rt.mae.verdict.good.body':  '95-Perzentil-MAE bei {p95}%. Du lässt Trades selten tief unter Wasser laufen — auch ohne SL diszipliniert.',
    'rt.mae.avg_mae':           'Ø MAE',
    'rt.mae.median':            'Median',
    'rt.mae.p95':               '95-Perzentil',
    'rt.mae.worst':             'Worst Case',
    'rt.mae.pct_account':       '{pct}% Konto',
    'rt.mae.distribution':      'MAE-Verteilung (% Konto)',
    'rt.mae.tooltip':           '{count} Trades · {pct}%',
    'rt.mae.recovery':          'Recovery-Rate',
    'rt.mae.recovery_hint':     'Trades, die aus negativem MAE in den Gewinn gerettet wurden. Hoch = Geduld zahlt sich aus. Niedrig = du hältst zu lange an Verlierern fest.',
    'rt.mae.giveback':          'Give-Back-Rate',
    'rt.mae.giveback_hint':     'Gewinner, die zu Verlust wurden (positives MFE, negativer Close). Hoch = du sicherst Gewinne nicht ab.',
    'rt.mae.rmae':              'Ø R-MAE',
    'rt.mae.rmae_hint':         'Ehrliches R-Multiple: realisierter P&L geteilt durch erlebten MAE. „Wie viel mitgenommen pro Einheit Schmerz?"',

    'rt.margin.title':          'Margin- & Exposure-Risiko',
    'rt.margin.info':           'Schätzt die Margin-Belegung pro Trade basierend auf Hebel und Notional-Value. Ohne SL ist die Margin-Distanz dein eigentliches „Stop-Loss“ — bei zu hoher Belegung kann eine kleine Marktbewegung dich liquidieren.',
    'rt.margin.leverage':       'Hebel 1:{lev}',
    'rt.margin.verdict.bad.title':  'Sehr hohe Hebel-Belegung',
    'rt.margin.verdict.bad.body':   'Im Schnitt sind {avg}% deines Kontos in Margin gebunden. Eine kleine Marktbewegung gegen dich kann zu Margin-Calls führen — ohne SL keine Reserve.',
    'rt.margin.verdict.warn.title': 'Moderate Hebel-Belegung',
    'rt.margin.verdict.warn.body':  'Ø {avg}% Margin-Belegung. Akzeptabel, aber maximal gleichzeitig {max}% — bei größeren Bewegungen wird\'s eng.',
    'rt.margin.verdict.good.title': 'Konservatives Sizing',
    'rt.margin.verdict.good.body':  'Nur {avg}% Margin pro Trade. Genug Puffer für Adverse Moves, auch ohne SL.',
    'rt.margin.avg':            'Ø Margin/Trade',
    'rt.margin.p95':            '95-Perzentil',
    'rt.margin.p95_hint':       '~Worst-Case-Trade',
    'rt.margin.max_parallel':   'Max. parallel',
    'rt.margin.max_parallel_hint': '{pct}% Konto gleichzeitig',
    'rt.margin.liq_move':       'Liquidations-Move',
    'rt.margin.liq_move_hint':  'gegen dich tolerierbar',
    'rt.margin.vol_cv':         'Volumen-Konsistenz',
    'rt.margin.vol_cv_low':     'Sehr konsistent — Sizing aus dem Plan.',
    'rt.margin.vol_cv_med':     'Moderate Streuung — okay, wenn bewusst.',
    'rt.margin.vol_cv_high':    'Stark schwankend — Verdacht auf Stimmungs-Sizing.',
    'rt.margin.margin_hours':   'Margin-Stunden',
    'rt.margin.margin_hours_hint': '$ × Stunden Margin-Belegung gesamt. Wenig sagt: kurze, fokussierte Trades. Viel: Kapital lange gebunden, mehr Tail-Exposure.',
    'rt.margin.footer':         'Margin grob geschätzt aus Notional ÷ Hebel — exakte Werte je nach Symbol-Spec leicht abweichend. Liquidations-Move = vereinfachte Schätzung für Einzeltrade, ignoriert weitere Positionen.',
    'rt.classic_divider':       'Klassisches SL-Modell (theoretisch)',

    // ── Coach Insights (titles + messages) ────────────────────
    'ci.high_wr.title':         'Hohe Win-Rate',
    'ci.high_wr.body':          '{wr}% Trefferquote über {n} Trades — du triffst öfter als du daneben liegst. Achte trotzdem darauf, dass deine Gewinner größer sind als deine Verlierer.',
    'ci.low_wr.title':          'Niedrige Win-Rate',
    'ci.low_wr.body':           'Nur {wr}% deiner Trades sind Gewinner. Das ist nicht zwangsläufig schlecht (Trend-Follower haben oft <40%) — aber deine R-Ratio muss dann stimmen. Check deinen Profit-Faktor unten.',
    'ci.strong_pf.title':       'Starker Profit-Faktor',
    'ci.strong_pf.body':        'Profit-Faktor {pf} — du verdienst pro $1 Verlust mehr als $2. Das ist eine saubere Edge.',
    'ci.weak_pf.title':         'Profit-Faktor unter 1',
    'ci.weak_pf.body':          'Du verlierst pro $1 Gewinn mehr als $1. Entweder Stops zu weit, Targets zu eng — oder du tradest gegen deine eigene Statistik. Schau dir die Pareto-Analyse und Best-vs-Worst an, um den Hebel zu finden.',
    'ci.thin_pf.title':         'Knapper Profit-Faktor',
    'ci.thin_pf.body':          'Profit-Faktor {pf} — knapp über break-even. Kleine Verschlechterung (mehr Spread, schlechtere Phase) und du bist rot. Lass die Verlierer kleiner werden oder Gewinner größer.',
    'ci.bad_rr.title':          'R:R unter 1',
    'ci.bad_rr.body':           'Dein durchschnittlicher Gewinner (${win}) ist kleiner als dein durchschnittlicher Verlierer (${loss}). Klassisches Symptom: Du schließt Gewinner zu früh aus Angst, Verlierer zu spät in der Hoffnung. Check die MFE/MAE-Capture-Rate.',
    'ci.good_rr.title':         'Solides R:R',
    'ci.good_rr.body':          'Durchschnittlicher Gewinner ist {rr}x so groß wie durchschnittlicher Verlierer. Du lässt Gewinner laufen — bleib dabei.',
    'ci.narrow_edge.title':     'Edge hängt an wenigen Trades',
    'ci.narrow_edge.body':      'Nur {n} von {total} Trades ({pct}%) machen 80% deines Bruttogewinns. Verlierst du diese Ausreißer (Glück? Spezielle Marktphase?), kollabiert deine Performance. Frage dich: wiederholbar?',
    'ci.broad_edge.title':      'Breite Edge',
    'ci.broad_edge.body':       '{n} von {total} Trades tragen den Gewinn — keine extreme Abhängigkeit von Einzel-Treffern. Deine Edge ist robust verteilt.',
    'ci.tilt.title':            'Tilt nach Verlusten',
    'ci.tilt.body':             'Nach einem Verlust fällt deine Win-Rate von {win}% auf {loss}% ({diff} Punkte Differenz). Klassischer Revenge-Trading-Indikator. Erzwinge eine Pause nach 2 Verlusten in Folge.',
    'ci.steady.title':          'Emotionale Stabilität',
    'ci.steady.body':           'Deine Win-Rate nach Verlusten ({loss}%) ist fast gleich wie nach Gewinnen ({win}%). Du tradest unabhängig vom vorherigen Ergebnis — das ist diszipliniertes Trading.',
    'ci.low_capture.title':     'Niedrige Gewinn-Capture',
    'ci.low_capture.body':      'Du nimmst im Schnitt nur {pct}% des verfügbaren Peak-Gewinns mit. Deine Trades laufen weiter als du sie hältst — entweder Take-Profit zu eng oder du steigst aus Angst zu früh aus.',
    'ci.high_capture.title':    'Starke Gewinn-Capture',
    'ci.high_capture.body':     '{pct}% Capture — du holst fast den ganzen Peak-Gewinn raus, ohne zu gierig zu werden. Sauberes Trade-Management.',
    'ci.volatile_months.title': 'Schwankende Monate',
    'ci.volatile_months.body':  'Hoher Variations-Koeffizient ({cv}) — deine Monatsergebnisse schwanken stark. Ein Lottogewinn-Monat zwischen flachen oder roten ist riskanter, als es der Gesamt-P&L wirken lässt.',
    'ci.consistent_returns.title': 'Konsistente Returns',
    'ci.consistent_returns.body':  'CV {cv} bei {greens} grünen Monaten — du lieferst gleichmäßig, nicht in Wellen. Das ist Prop-Firm-tauglich.',
    'ci.low_recovery.title':    'Schmerz größer als Gewinn',
    'ci.low_recovery.body':     'Recovery-Factor {rf} — dein Max-Drawdown war größer als dein Gesamt-Gewinn. Du musstest mehr riskieren, als du verdient hast.',
    'ci.high_recovery.title':   'Hohe Schmerz-Effizienz',
    'ci.high_recovery.body':    'Recovery-Factor {rf} — du verdienst >5x das, was du im tiefsten Drawdown im Loch warst. Sehr robuste Kurve.',
    'ci.high_ror.title':        'Risiko zu hoch',
    'ci.high_ror.body':         'Risk-of-Ruin liegt bei {pct}%. Bei deiner aktuellen WR/R-Ratio und Risiko-Größe ist das nicht spekulativ — das wird passieren. Reduziere Risiko pro Trade auf <1%.',
    'ci.long_streak.title':     'Lange Verlierer-Serie',
    'ci.long_streak.body':      'Längste Verlust-Serie: {n} Trades. Stelle sicher, dass deine Positionsgröße sowas ohne Panik überlebt — bei 2% Risiko = ~13% Drawdown ohne Compound-Effekt.',
    'ci.fallback.title':        'Solides Mittelfeld',
    'ci.fallback.body':         'Keine Extremwerte auf den ersten Blick. Schau dir die einzelnen Karten unten an — der Teufel steckt im Detail (Heatmap-Zeiten, Tag-Kombinationen, Hold-Time-Verteilung).',
  },
  en: {
    // ── App-wide
    'app.privacy':            'Privacy',
    'app.live_mt5_equity':    'Live MT5 equity',
    'app.starting_capital':   'Starting capital',
    'app.starting_capital.hint': 'Once MT5 is connected, the live equity is used automatically.',
    'app.starting_capital.live_hint': 'ROI base is taken directly from your MT5 account — no manual entry needed.',
    'app.ok':                 'OK',

    // ── Sidebar
    'nav.dashboard':       'Dashboard',
    'nav.journal':         'Trade Journal',
    'nav.daily_journal':   'Daily Journal',
    'nav.calendar':        'Calendar',
    'nav.analyse':         'Analysis',
    'nav.setups':          'Setups',
    'nav.risk':            'Risk',
    'nav.profile':         'Profile',
    'nav.import':          'Import',
    'nav.export':          'Export',
    'nav.live':            'Live',
    'nav.offline':         'Offline',
    'nav.mt5_disconnected':'MT5 disconnected',
    'nav.trading_journal': 'Trading Journal',

    // ── Common
    'common.save':         'Save',
    'common.saved':        'Saved',
    'common.cancel':       'Cancel',
    'common.delete':       'Delete',
    'common.confirm':      'Confirm',
    'common.confirm_q':    'Really delete?',
    'common.back':         'Back',
    'common.close':        'Close',
    'common.search':       'Search',
    'common.filter':       'Filter',
    'common.reset':        'Reset',
    'common.add':          'Add',
    'common.edit':         'Edit',
    'common.copy':         'Copy',
    'common.copied':       'Copied!',
    'common.download':     'Download',
    'common.upload':       'Upload',
    'common.all':          'All',
    'common.none':         'None',
    'common.from':         'From',
    'common.to':           'To',
    'common.symbol':       'Symbol',
    'common.type':         'Type',
    'common.volume':       'Volume',
    'common.volume_short': 'Vol.',
    'common.price':        'Price',
    'common.entry':        'Entry',
    'common.exit':         'Exit',
    'common.open':         'Open',
    'common.current':      'Current',
    'common.duration':     'Duration',
    'common.pnl':          'P&L',
    'common.profit':       'Profit',
    'common.loss':         'Loss',
    'common.trades':       'Trades',
    'common.trade':        'Trade',
    'common.win_rate':     'Win Rate',
    'common.profit_factor':'Profit Factor',
    'common.notes':        'Notes',
    'common.tags':         'Tags',
    'common.tag':          'Tag',
    'common.date':         'Date',
    'common.day':          'Day',
    'common.week':         'Week',
    'common.month':        'Month',
    'common.year':         'Year',
    'common.all_time':     'All',
    'common.today':        'Today',
    'common.yesterday':    'Yesterday',
    'common.this_week':    'This week',
    'common.last_week':    'Last week',
    'common.this_month':   'This month',
    'common.last_month':   'Last month',
    'common.this_year':    'This year',
    'common.last_year':    'Last year',
    'common.all_times':    'All time',
    'common.generated_at': 'Generated on',
    'common.last_update':  'Last update',
    'common.never':        'Never',
    'common.no_trades':    'No trades yet',
    'common.no_trades_found': 'No trades found',
    'common.no_data':      'No data',
    'common.loading':      'Loading...',
    'common.failed':       'Failed',
    'common.success':      'Success',
    'common.preview':      'Preview',
    'common.timeframe':    'Period',
    'common.trading_days': 'Trading days',
    'common.connected':    'connected',
    'common.not_connected':'not connected',
    'common.position':     'position',
    'common.positions':    'positions',

    // ── Trade Journal
    'journal.title':          'Trade Journal',
    'journal.add_trade':      'Add trade',
    'journal.sync':           'Sync',
    'journal.syncing':        'Syncing…',
    'journal.search_placeholder': 'Search by symbol, note, tag...',
    'journal.more_filters':   'More filters',
    'journal.groups_detected':'detected',
    'journal.x_of_y_filtered':'{shown} of {total} trades filtered',
    'journal.selected':       '{count} selected',
    'journal.deselect':       'Deselect',
    'journal.bulk_delete':    'Delete',
    'journal.delete_trade':   'Delete trade',
    'journal.delete_confirm': 'Really delete this trade?',
    'journal.trade_deleted':  'Trade deleted',
    'journal.trades_deleted': '{count} trades deleted',
    'journal.undo':           'Undo',
    'journal.undo_hint':      'Click Undo to restore',
    'journal.dissolve_group': 'Dissolve group',
    'journal.remove_from_group': 'Remove from group',
    'journal.no_autogroup':   'Do not auto-group',
    'journal.enable_autogroup': 'Enable auto-group',
    'journal.drag_hint':      'Group trades manually via drag & drop — just drag one row onto another.',
    'journal.col_avg_entry':  'Avg Entry',
    'journal.col_avg_exit':   'Avg Exit',
    'journal.symbol_choose':  'Choose symbol',
    'journal.cat_all':         'All',
    'journal.cat_forex':       'Forex',
    'journal.cat_commodities': 'Commodities',
    'journal.cat_indices':     'Indices',
    'journal.cat_crypto':      'Crypto',
    'journal.cat_stocks':      'Stocks',
    'journal.tag_all':         'All tags',
    'journal.sync_done':       'Sync successful',
    'journal.sync_failed':     'Sync failed',
    'journal.sync_already_up_to_date': 'Already up to date',
    'journal.sync_updated':    '{count} updated',
    'journal.sync_new':        '{count} new',
    'journal.sync_x_from_mt5': '{parts} from MT5',
    'journal.sync_x_in_backend': '{count} trades in backend, all in sync',
    'journal.manual':         'manual',
    'journal.select_all':     'Select all',
    'journal.groups':         'Groups',

    // ── Trade Detail Modal
    'modal.opened':          'Opened',
    'modal.closed':          'Closed',
    'modal.new_tag':         'New tag...',
    'modal.mark_mistakes':   'Mark mistakes (optional — honesty pays off)',
    'modal.mistakes_hint':   'These markers feed into the mistake-cost analysis on the Analysis page.',
    'modal.notes_placeholder': 'Trade analysis, emotions, improvements...',
    'modal.setup_label':     'Setup',
    'modal.no_setup':        '— No setup assigned —',
    'modal.setup_target_rr': 'Target R:R',
    'modal.opening':         'Open',
    'modal.closing':         'Close',
    'modal.lot':             'Lot',
    'modal.stop_loss':       'Stop Loss',
    'modal.take_profit':     'Take Profit',
    'modal.commission':      'Commission',
    'modal.swap':            'Swap',
    'modal.gross_profit':    'Gross profit',
    'modal.net_pnl':         'Net P&L',

    // ── Add Trade Modal
    'add.title':             'Add trade',
    'add.commission':        'Commission',
    'add.swap':              'Swap',
    'add.add_trade':         'Add trade',

    // ── Live Sync Panel
    'live.open_positions':   'Open Positions',
    'live.groups':           '{count} group',
    'live.groups_plural':    '{count} groups',
    'live.no_positions':     'No open positions',
    'live.mt5_connected':    'TMGM MT5 connected',
    'live.mt5_not_connected':'MT5 not connected',
    'live.connection_info':  '{trade_count} trades · {pos_count} position',
    'live.col_risk_reward':  'Risk/Reward',
    'live.position_note':    'Position note',
    'live.note_placeholder': 'Why did I enter? Setup, bias, levels...',
    'live.add_tag':          'Add tag...',
    'live.account':          'Account',
    'live.balance':          'Balance',
    'live.equity':           'Equity',
    'live.open_pnl':         'Open P&L',
    'live.margin_level':     'Margin Level',
    'live.x_imported':       '{count} trade imported',
    'live.x_imported_plural':'{count} trades imported',
    'live.auto_imported':    'Automatically synced from MT5',

    // ── Setup Library
    'setups.title':            'Setup Library',
    'setups.subtitle':         'Your trading playbooks',
    'setups.setups_defined':   '{count} setup defined',
    'setups.setups_defined_plural': '{count} setups defined',
    'setups.unassigned':       '{count} trades not yet assigned',
    'setups.new_setup':        'New setup',
    'setups.edit_setup':       'Edit setup',
    'setups.no_setups':        'No setups defined yet',
    'setups.no_setups_hint':   'Define your trading setups as reusable playbooks. Each trade can later be assigned to a setup so you can see which strategies actually make money.',
    'setups.field_name':       'Name',
    'setups.field_color':      'Color',
    'setups.field_description':'Description',
    'setups.desc_placeholder': 'In which market phase do you use this? What is the thesis?',
    'setups.field_target_rr':  'Target R:R',
    'setups.field_max_risk':   'Max risk %',
    'setups.entry_rules':      'Entry rules',
    'setups.exit_rules':       'Exit rules',
    'setups.entry_placeholder':'e.g. Price above daily VWAP',
    'setups.exit_placeholder': 'e.g. SL below last low',
    'setups.add_rule':         'Add rule',
    'setups.create':           'Create setup',
    'setups.delete_confirm':   'Really delete setup "{name}"?',
    'setups.entry_section':    'Entry:',
    'setups.exit_section':     'Exit:',
    'setups.more_rules':       '… +{count} more',
    'setups.risk':             'Risk',

    // ── Profile / Share
    'profile.title':            'Profile',
    'profile.subtitle':         'Share your trading performance — no absolute dollar amounts',
    'profile.share_export':     'Share & Export',
    'profile.copy_image':       'Copy image to clipboard',
    'profile.image_copied':     'Image copied!',
    'profile.creating_image':   'Creating image…',
    'profile.copy_image_hint':  'PNG to clipboard — perfect for posting',
    'profile.paste_hint':       'Paste with Ctrl+V into Discord, Telegram, etc.',
    'profile.download_png':     'Download PNG',
    'profile.download_png_hint':'Saves the share card as a high-resolution image',
    'profile.copy_link':        'Copy link',
    'profile.link_copied':      'Link copied!',
    'profile.copy_link_hint':   'URL with Base64-encoded stats — read-only view',
    'profile.export_pdf':       'Export PDF',
    'profile.export_pdf_hint':  'Prints only the share card, no navigation',
    'profile.share_safe_hint':  'Image, PDF & link contain no absolute dollar amounts.',
    'profile.no_dollar':        'No absolute dollar amounts',
    'profile.included_metrics': 'Included metrics',
    'profile.no_trades_in_period':'No trades in this period',
    'profile.review_day':       'Daily review',
    'profile.review_week':      'Weekly review',
    'profile.review_month':     'Monthly review',
    'profile.review_year':      'Yearly review',
    'profile.review_all':       'Overall performance',
    'profile.best_trade':       'Best trade',
    'profile.top_n_trades':     'Top {count} Trade',
    'profile.top_n_trades_plural':'Top {count} Trades',
    'profile.avg_trades_day':   'Avg trades/day',
    'profile.go_to_today':      'Back to current period',
    'profile.prev_day':         'Previous day',
    'profile.prev_week':        'Previous week',
    'profile.prev_month':       'Previous month',
    'profile.prev_year':        'Previous year',
    'profile.next_period':      'Next period',
    'profile.future':           'Future',
    'mb.title':                 'Mentor Brief',
    'mb.subtitle':              'Structured performance summary to share with coach/AI mentor.',
    'mb.privacy_mode':          'Privacy mode',
    'mb.privacy_full':          'Full',
    'mb.privacy_full_desc':     '$ amounts',
    'mb.privacy_relative':      'R-multiples',
    'mb.privacy_relative_desc': 'Risk-relative',
    'mb.privacy_anonymous':     'Anonymous',
    'mb.privacy_anonymous_desc':'Ratios only',
    'mb.share_notes':           'Share notes',
    'mb.focus_label':           'Focus for the session (optional)',
    'mb.focus_placeholder':     "What do you want to talk about? e.g. 'Why do I overtrade after losses? Which setup should I drop?'",
    'mb.generate':              'Generate brief',
    'mb.copy_md':               'Copy markdown',
    'mb.copy_md_done':          'Copied!',
    'mb.show_preview':          'Show preview',
    'backup.title':             'Backup & Restore',
    'backup.subtitle':          'All trades, tags, groups & notes live locally in your browser — JSON export protects against data loss.',
    'backup.export':            'Export backup (JSON)',
    'backup.export_hint':       '{trades} trades, {notes} position notes',
    'backup.restore':           'Restore backup',
    'backup.restore_hint':      'Overwrites current trades, tags and notes',
    'backup.restore_confirm':   'Restore backup?',
    'backup.restore_file':      'File',
    'backup.restore_exported':  'Exported',
    'backup.restore_trades_in_backup': 'Trades in backup',
    'backup.restore_warning':   'Warning: current trades, tags, groups and notes will be completely overwritten. Are you sure you want to continue?',
    'backup.restore_action':    'Restore',

    // ── Dashboard / Analyse common
    'dash.equity_curve':        'Equity Curve',
    'dash.monthly_pnl':         'Monthly P&L',
    'dash.drawdown':            'Drawdown',
    'dash.hold_duration':       'Avg Hold by Symbol',
    'dash.pnl_by_symbol':       'P&L by Symbol',
    'dash.total_pnl':           'Total P&L',
    'dash.roi':                 'ROI',
    'dash.avg_rr':              'Avg R:R',
    'dash.basis':               'Base',
    'dash.winners':             '{count} winners',
    'dash.choose_timeframe':    'Choose timeframe',
    'dash.apply':               'Apply',
    'dash.choose_date':         'Choose custom range',
    'dash.date_short':          'Date',
    'dash.tf_1d':               '1D',
    'dash.tf_1w':               '1W',
    'dash.tf_1m':               '1M',
    'dash.tf_3m':               '3M',
    'dash.tf_6m':               '6M',
    'dash.tf_1y':               '1Y',
    'dash.tf_all':              'All',
    'dash.x_of_y_filtered':     '{shown} of {total} trades filtered',
    'dash.x_trades_pos_grouped':'({positions} positions, {groups} grouped)',
    'dash.excellent':           'Excellent',
    'dash.good':                'Good',
    'dash.bad':                 'Bad',
    'dash.improve':             'Improve',
    'dash.basis_label':         'Basis',
    'dash.win_rate':            'Win Rate',
    'dash.trades_label':        'Trades',
    'dash.symbol_col':          'Symbol',
    'dash.winners_col':         'Winners',
    'dash.pnl':                 'P&L',

    // ── Risk
    'risk.title':               'Risk Analysis',
    'risk.based_on':            'Based on {pct}% risk per trade',
    'risk.avg_risk':            'Avg risk per trade',
    'risk.max_risk':            'Max risk per trade',
    'risk.fixed_model':         'Fixed risk model',
    'risk.avg_r_multiple':      'Avg R-multiple',
    'risk.expectancy_positive': 'Profitable expectancy',
    'risk.expectancy_negative': 'Negative expectancy',
    'risk.r_distribution':      'R-multiple distribution',
    'risk.all_trades':          'All trades',
    'risk.tilt_detector':       'Tilt detector',
    'risk.tilt_subtitle':       'Behavior after loss streaks',
    'risk.tilt_need_data':      'At least 5 trades after winning phases needed for baseline — currently {count}.',
    'risk.tilt_normal':         'Baseline',
    'risk.tilt_normal_desc':    'After win / start',
    'risk.tilt_one_loss':       '1 loss before',
    'risk.tilt_first_loss':     'First defeat',
    'risk.tilt_two_losses':     '2 losses before',
    'risk.tilt_frustzone':      'Frustration zone',
    'risk.tilt_three_plus':     '3+ losses before',
    'risk.tilt_zone':           'Tilt zone',
    'risk.tilt_too_little_data':'Too little data',
    'risk.tilt_no_pattern':     'No tilt pattern detected — you keep discipline after loss streaks. Strong.',
    'risk.avg_volume':          'Avg volume',
    'risk.avg_pnl':             'Avg P&L',
    'risk.avg_r':               'Avg R',

    // ── Analyse Section Titles
    'an.title':                 'Analysis',
    'an.subtitle':              '{count} deep analytics — based on {trades} trades.',
    'an.empty':                 'No closed trades yet — this page comes alive once you have some.',
    'an.forecast':              'Equity Forecast',
    'an.forecast_subtitle':     'If your average from the last {range} continues.',
    'an.coach':                 'Coach mode — Weekly review',
    'an.coach_subtitle':        'Week starting {date} · vs. last week',
    'an.yearly':                'Trading year at a glance',
    'an.pareto':                'Pareto analysis: Who carries your account?',
    'an.whatif':                'What-if simulator',
    'an.holdtime':              'Hold time vs. result',
    'an.best_vs_worst':         'Best vs Worst — top 10 vs bottom 10',
    'an.streak':                'Streak statistics',
    'an.sequence':              'Sequential bias / revenge trading',
    'an.heatmap':               'Performance heatmap (day × hour)',
    'an.mfe_mae':               'MFE/MAE capture rate',
    'an.mistakes':              'Mistake cost analysis',
    'an.ulcer':                 'Ulcer index & recovery',
    'an.recovery':              'Recovery factor',
    'an.ror':                   'Risk-of-ruin & Kelly',
    'an.tag_matrix':            'Tag combo matrix',
    'an.vol_norm':              'Volatility-normalized returns',
    'an.consistency':           'Consistency score',
    'fc.basis':                 'Base',
    'fc.mode':                  'Mode',
    'fc.compound':              'Compound',
    'fc.linear':                'Linear',
    'fc.forecast':              'Forecast',
    'fc.target':                'Daily target',
    'fc.workday':               '/ weekday',
    'fc.disable_target':        'Disable daily target',
    'fc.avg_return_day':        'Avg return / day',
    'fc.avg_pnl_day':           'Avg P&L / day',
    'fc.current_equity':        'Current equity',
    'fc.in_x_days':             'In {days} days',
    'fc.expected_return':       'Expected return',
    'fc.x_trading_days':        '{count} trading days',
    'fc.vs_balance':            'vs. {label} ${value}',
    'fc.starting_capital':      'starting capital',
    'fc.mt5_equity':            'MT5 equity',
    'fc.if_pace_continues':     'If pace continues — goals',
    'fc.doubling':              'Doubling',
    'fc.plus_25':               '+25%',
    'fc.next_1k':               'Next $1k mark',
    'fc.reached':               '✓ reached',
    'fc.x_days':                '{days} days',
    'fc.x_years':                '{years} years',
    'fc.negative_pace':         'Current performance is negative — at this pace the account is melting. Switch to a larger base ({all}) for a more realistic picture, or fix the strategy first.',
    'fc.legend_actual':         'Actual equity',
    'fc.legend_forecast':       'Forecast (avg of last {range})',
    'fc.legend_target':         'Target ({pct}% / weekday, weekends flat)',
    'fc.confidence_band':       'Shaded area = ±1σ confidence band (~68% of paths inside).',
    'fc.compound_note':         'Compound mode: daily return is applied to the growing equity.',
    'fc.linear_note':           'Linear mode: fixed dollar amount per day, no reinvestment.',
    'fc.ahead_of_target':       '{pct}% above target',
    'fc.behind_target':         '{pct}% below target',
    'fc.target_explainer':      'At {pct}% per weekday you should be at ${target} now, but you are at ${current}. · Goal in {days} days: ${final}',
    'an.now':                   'Now',
    'an.start':                 'Start',

    // ── Setup Wizard ──────────────────────────────────────────
    'setup.welcome':            'Welcome to TradeStats',
    'setup.welcome_subtitle':   'For this web app to see your MT5 trades, you need the TradeStats Connector on your PC — just once. Takes ~2 minutes.',
    'setup.banner.offline.title':       'Connector not started yet',
    'setup.banner.offline.body':        'TradeStats Connector at {url} is not reachable.',
    'setup.banner.backend_only.title':  'Connector running — MT5 missing',
    'setup.banner.backend_only.body':   'MetaTrader 5 is not connected. Please open MT5 and log in.',
    'setup.banner.checking.title':      'Checking connection...',
    'setup.checking':                   'Connecting to TradeStats Connector...',
    'setup.step1.title':                'Download the Connector',
    'setup.step1.body':                 'Download the TradeStats Connector — a small program that feeds your MT5 data into this web app.',
    'setup.step1.action':               'Download Connector',
    'setup.step2.title':                'Run the installer',
    'setup.step2.body':                 'Double-click TradeStats_Setup.exe. Follow the setup wizard — no special options needed. Takes about 30 sec.',
    'setup.step3.title':                'Open MetaTrader 5',
    'setup.step3.body':                 'Start your MT5 terminal and log in to your account. The Connector uses the MT5 Python API and needs an active terminal login.',
    'setup.step3.hint':                 'A demo account works the same as a live account.',
    'setup.step4.title':                'Start the Connector',
    'setup.step4.body':                 'Launch the TradeStats Connector (desktop shortcut or Start menu). A console window opens and stays open. Don\'t close it — keep it open while you trade.',
    'setup.step4.body_done':            'Connector is running ✓ — we\'re just waiting for the MT5 connection.',
    'setup.step4.hint':                 'If Windows Firewall asks: "Allow access" — the Connector only listens on localhost (127.0.0.1).',
    'setup.success.title':              'Connector connected!',
    'setup.success.body':               'Loading your trades now... redirecting in a moment.',
    'setup.waiting_hint':               'I\'m checking every 3 seconds whether the Connector is reachable. Once it\'s running, this advances automatically — no clicking needed here.',
    'setup.about_connector':            'What is the Connector?',
    'setup.skip_csv':                   'Continue without Connector (CSV import)',
    'setup.badge.offline':              'Connector offline',
    'setup.badge.mt5_off':              'MT5 not connected',
    'setup.badge.show_tooltip':         'Show setup guide again',
    'setup.trades_count':               '{count} trade{plural}',
    // SmartScreen hint
    'setup.ss.toggle':                  'Windows shows a warning? That\'s normal — here\'s how to click through it',
    'setup.ss.explain':                 'On first launch, {dfdr} blocks the installer because it\'s not signed by Microsoft. Code-signing certificates cost 300+ €/year — not worth it for a hobby project. The code is {github}, so you can verify yourself that nothing malicious is in it.',
    'setup.ss.defender':                'Windows Defender SmartScreen',
    'setup.ss.github_open':             'openly viewable on GitHub',
    'setup.ss.protected_title':         'Windows protected your PC',
    'setup.ss.body1':                   'Microsoft Defender SmartScreen prevented an unrecognized app from starting.',
    'setup.ss.more_info':               'More info',
    'setup.ss.click_1':                 '← 1. Click here',
    'setup.ss.click_2':                 '2. Click here →',
    'setup.ss.dont_run':                'Don\'t run',
    'setup.ss.run_anyway':              'Run anyway',
    'setup.ss.between':                 'Then a new button appears:',
    'setup.ss.app_label':               'App:',
    'setup.ss.footer':                  'Once you\'ve clicked "Run anyway" the first time, Windows remembers your decision — the warning won\'t appear again on subsequent launches.',

    // ── Hold Duration Trend ───────────────────────────────────
    'hd.title':                 'Avg. hold duration per day',
    'hd.subtitle':              '{days} trading days · overall average: {avg}',
    'hd.empty_subtitle':        'No trades in the selected period',
    'hd.empty_hint':            'Pick a different time range.',
    'hd.info':                  'Average hold duration of all trades per trading day, plus a 7-day rolling average (smoothed line) for trend detection. Useful for seeing whether you let trades run longer over time (more patience) or exit faster (fear/impatience) — both behavioral signals matter for your edge.',
    'hd.range_label':           'Range:',
    'hd.range.month':           'Month',
    'hd.range.year':            'Year',
    'hd.range.all':             'All',
    'hd.trades_count':          '{n} trades',
    'hd.first_half':            'First half',
    'hd.second_half':           'Second half',
    'hd.trend.up':              'Hold duration has risen by {pct}% — you\'re holding longer than before.',
    'hd.trend.down':            'Hold duration has dropped by {pct}% — you\'re exiting faster.',
    'hd.trend.stable':          'Hold duration is unchanged (±{pct}%).',
    'hd.legend':                'Teal bars = daily average · Orange line = 7-day rolling average (smoothed) · Grey line = overall average of all trades.',
    'hd.tooltip.day':           'Day avg: {value}',
    'hd.tooltip.rolling':       '7-day avg: {value}',

    // ── Sizing Consistency ────────────────────────────────────
    'sc.title':                 'Sizing consistency',
    'sc.subtitle':              'Avg. position: {avg} lot · max deviation: {dev}%',
    'sc.info':                  'Compares your average position size (lot volume) based on prior-trade context. Statistically you should always risk the same — if you size up or down after losses, that\'s emotion-driven and erodes your edge. Biggest lever: sizing drift often explains the most painful drawdowns.',
    'sc.bucket.opening':        'Opening trade',
    'sc.bucket.afterWin':       'After win',
    'sc.bucket.afterLoss':      'After loss',
    'sc.bucket.after2Loss':     'After 2+ losses',
    'sc.bucket.afterBigLoss':   'After big loss',
    'sc.verdict.bad.title':     'Strongly inconsistent',
    'sc.verdict.bad.body':      'Up to {dev}% deviation — you size very differently depending on mood. Classic tilt/overconfidence symptom.',
    'sc.verdict.warn.title':    'Slightly inconsistent',
    'sc.verdict.warn.body':     '{dev}% deviation. Still acceptable but watch it — sizing should come from a plan, not from the last trade.',
    'sc.verdict.good.title':    'Consistent',
    'sc.verdict.good.body':     'Only {dev}% deviation between buckets. You size with discipline regardless of prior trades.',
    'sc.trades_count':          '{n} trade{plural}',
    'sc.lot_unit':              '{n} lot',
    'sc.wr':                    'WR',
    'sc.legend':                'Vertical line = overall average across all trades. Bar position shows deviation. Red above ±25%, yellow above ±10%.',

    // ── Concurrent Positions ──────────────────────────────────
    'cp.title':                 'Concurrent positions',
    'cp.subtitle':              'Avg {avg} open in parallel · max {max} · {solo}% solo trades',
    'cp.info':                  'Measures how many other positions are typically open at the same time when you open a new trade. If you hold 3 USD pairs long simultaneously, you really have one "dollar weakness" trade with 3× risk. The symbol pairs below show which combinations most often run concurrently — check correlations.',
    'cp.verdict.good.title':    'Cleanly sequential',
    'cp.verdict.good.body':     'On average only {avg} other position open. {solo}% of your trades are solo — clean, focused trading without cluster risk.',
    'cp.verdict.warn.title':    'Moderate overlap',
    'cp.verdict.warn.body':     'Avg {avg} other positions open, max {max}. Watch whether the symbols are correlated — otherwise you\'re silently multiplying your risk.',
    'cp.verdict.bad.title':     'High concentration',
    'cp.verdict.bad.body':      'Avg {avg} other positions — you hold a lot at the same time. If the symbols correlate, you\'re effectively on 1 trade with {max}× risk. A very underestimated drawdown source.',
    'cp.top_pairs':             'Most frequent symbol pairs (open at the same time)',
    'cp.overlap_times':         '{count}× overlapped',
    'cp.overlap_hours':         '{hours}h together',
    'cp.no_overlap':            'No time-overlapping trades — you trade strictly sequentially.',
    'cp.tip':                   'Tip: Check correlation for top pairs (e.g. EURUSD/GBPUSD ≈ 0.85). High positive correlation = effectively doubled risk.',

    // ── Trading Frequency Trend ───────────────────────────────
    'tf.title':                 'Trading frequency trend',
    'tf.subtitle':              'Avg {avg} trades per day · {days} trading days',
    'tf.info':                  'Number of trades per day with 7-day rolling average and concurrent win rate. Classic overtrading pattern: frequency rises + win rate falls → you\'re no longer taking only A-setups but also B and C grades. Early indicator of tilt or boredom-trading.',
    'tf.verdict.overtrading.title': 'Overtrading warning',
    'tf.verdict.overtrading.body':  'Your trade frequency has risen by {freq}% and your win rate dropped by {wr} points. Classic pattern: more trades, lower quality.',
    'tf.verdict.rising.title':  'Frequency rising',
    'tf.verdict.rising.body':   '{freq}% more trades per day — win rate still holding ({wr_sign}{wr} pts). Stay alert that quantity doesn\'t replace quality.',
    'tf.verdict.falling.title': 'Frequency falling',
    'tf.verdict.falling.body':  '{freq}% fewer trades. Either more selective, or a phase with fewer setups — win rate change: {wr_sign}{wr} pts.',
    'tf.verdict.stable.title':  'Stable frequency',
    'tf.verdict.stable.body':   'Trade count constant (±{freq}%). Solid routine — discipline shows.',
    'tf.first_half':            'First half',
    'tf.second_half':           'Second half',
    'tf.trades_per_day':        'trades/day',
    'tf.legend':                'Orange = trades/day (bars + 7-day line) · Blue dashed = 7-day win rate (right axis). When orange rises AND blue falls: overtrading suspected.',

    // ── AI Coach ──────────────────────────────────────────────
    'coach.title':              'AI coach',
    'coach.subtitle':           '{count} insights · {good} strengths · {bad} critical · {tip} hints',
    'coach.info':               'Auto-generated assessment of your performance across all metrics: what\'s working, where risk is hiding, where concrete improvements are possible. Thresholds are based on established trading-statistics standards (profit factor, R-ratio, recovery factor, risk of ruin). No crystal ball — data-driven hypotheses to test in your next trade plan.',
    'coach.no_data':            'Too few trades for a solid assessment — at least 10 closed trades help.',
    'coach.core_points':        'Core points',
    'coach.severity.good':      'Strong',
    'coach.severity.warn':      'Caution',
    'coach.severity.bad':       'Risk',
    'coach.severity.tip':       'Hint',
    'coach.intro':              'I ran your {count} closed trades through every analytics module. Here\'s what I see:',
    'coach.positive_lead':      '**What you\'re doing right:**',
    'coach.positive_close.single': 'One clear bright spot overall — stick with these patterns ({headlines}).',
    'coach.positive_close.multi':  'Overall {n} bright spots — stick with these patterns ({headlines}).',
    'coach.positive_none':      '**What you\'re doing right:** Nothing stands out on the headline metrics — not a disaster, but not a cushion either. Focus on building at least one strength before tweaking many levers at once.',
    'coach.critical_lead':      '**What\'s costing you right now:**',
    'coach.critical_close':     'If you fixed one thing this week, fix the first item above — that\'s where the biggest lever is.',
    'coach.critical_none':      '**What\'s costing you right now:** No red flags on the main metrics. Caveat: this is a snapshot — small samples can hide risks. Stick with strict risk management.',
    'coach.outlook_lead':       '**Worth thinking about:**',

    // ── MAE Risk + Margin Exposure (Risk Tab) ────────────────
    'rt.mae.title':             'Realized risk (MAE)',
    'rt.mae.empty':             'Not enough MFE/MAE data yet',
    'rt.mae.empty_body':        'MFE/MAE tracking runs in the background via Live Sync. Once enough trades are archived ({count} so far), your realized risk profile will appear here.',
    'rt.mae.subtitle':          '{count} trades with MFE/MAE',
    'rt.mae.info':              'Maximum Adverse Excursion: how deep a trade actually went into drawdown before closing. For traders without a fixed SL, this is the most honest risk indicator.',
    'rt.mae.verdict.bad.title': 'High realized risk',
    'rt.mae.verdict.bad.body':  '95% of your trades stayed under {p95}% drawdown — but that also means 5% went deeper. On your account that\'s ~${abs} of pain per trade. Without an SL, the tail worst-case is your actual risk.',
    'rt.mae.verdict.warn.title': 'Moderate risk',
    'rt.mae.verdict.warn.body':  '95-percentile MAE sits at {p95}% of the account. Acceptable, but watch it — that\'s your "1 in 20 trades" worst-case.',
    'rt.mae.verdict.good.title': 'Controlled drawdowns',
    'rt.mae.verdict.good.body':  '95-percentile MAE at {p95}%. You rarely let trades go deep underwater — disciplined even without an SL.',
    'rt.mae.avg_mae':           'Avg MAE',
    'rt.mae.median':            'Median',
    'rt.mae.p95':               '95-percentile',
    'rt.mae.worst':             'Worst case',
    'rt.mae.pct_account':       '{pct}% account',
    'rt.mae.distribution':      'MAE distribution (% account)',
    'rt.mae.tooltip':           '{count} trades · {pct}%',
    'rt.mae.recovery':          'Recovery rate',
    'rt.mae.recovery_hint':     'Trades saved from negative MAE into a winning close. High = patience pays. Low = you hold losers too long.',
    'rt.mae.giveback':          'Give-back rate',
    'rt.mae.giveback_hint':     'Winners that turned into losses (positive MFE, negative close). High = you\'re not protecting profits.',
    'rt.mae.rmae':              'Avg R-MAE',
    'rt.mae.rmae_hint':         'Honest R multiple: realized P&L divided by the MAE you actually experienced. "How much taken per unit of pain?"',

    'rt.margin.title':          'Margin & exposure risk',
    'rt.margin.info':           'Estimates margin usage per trade based on leverage and notional value. Without an SL, margin distance is your actual "stop loss" — if usage is too high, a small market move can liquidate you.',
    'rt.margin.leverage':       'Leverage 1:{lev}',
    'rt.margin.verdict.bad.title':  'Very high leverage usage',
    'rt.margin.verdict.bad.body':   'On average {avg}% of your account is tied up in margin. A small adverse move can trigger margin calls — without an SL, no reserve.',
    'rt.margin.verdict.warn.title': 'Moderate leverage usage',
    'rt.margin.verdict.warn.body':  'Avg {avg}% margin usage. Acceptable, but at peak {max}% concurrent — bigger moves get tight.',
    'rt.margin.verdict.good.title': 'Conservative sizing',
    'rt.margin.verdict.good.body':  'Only {avg}% margin per trade. Plenty of buffer for adverse moves, even without an SL.',
    'rt.margin.avg':            'Avg margin/trade',
    'rt.margin.p95':            '95-percentile',
    'rt.margin.p95_hint':       '~worst-case trade',
    'rt.margin.max_parallel':   'Max parallel',
    'rt.margin.max_parallel_hint': '{pct}% account at the same time',
    'rt.margin.liq_move':       'Liquidation move',
    'rt.margin.liq_move_hint':  'tolerable against you',
    'rt.margin.vol_cv':         'Volume consistency',
    'rt.margin.vol_cv_low':     'Very consistent — sizing from a plan.',
    'rt.margin.vol_cv_med':     'Moderate spread — fine if intentional.',
    'rt.margin.vol_cv_high':    'High variation — suspected mood sizing.',
    'rt.margin.margin_hours':   'Margin-hours',
    'rt.margin.margin_hours_hint': 'Total $ × hours of margin usage. Low = short focused trades. High = capital tied up long, more tail exposure.',
    'rt.margin.footer':         'Margin roughly estimated as notional ÷ leverage — exact values depend on per-symbol specs. Liquidation move = simplified single-trade estimate, ignoring other positions.',
    'rt.classic_divider':       'Classic SL model (theoretical)',

    // ── Coach Insights (titles + messages) ────────────────────
    'ci.high_wr.title':         'High win rate',
    'ci.high_wr.body':          '{wr}% hit rate across {n} trades — you hit more often than you miss. Still, make sure your winners are bigger than your losers.',
    'ci.low_wr.title':          'Low win rate',
    'ci.low_wr.body':           'Only {wr}% of your trades are winners. Not necessarily bad (trend-followers often run <40%) — but your R-ratio needs to compensate. Check your profit factor below.',
    'ci.strong_pf.title':       'Strong profit factor',
    'ci.strong_pf.body':        'Profit factor {pf} — you earn more than $2 for every $1 lost. That\'s a clean edge.',
    'ci.weak_pf.title':         'Profit factor below 1',
    'ci.weak_pf.body':          'You lose more than $1 for every $1 gained. Either stops too wide, targets too tight — or you\'re trading against your own statistics. Check the Pareto analysis and Best vs Worst to find the lever.',
    'ci.thin_pf.title':         'Thin profit factor',
    'ci.thin_pf.body':          'Profit factor {pf} — just above break-even. A small worsening (more spread, weaker phase) and you\'re red. Make losers smaller or winners bigger.',
    'ci.bad_rr.title':          'R:R below 1',
    'ci.bad_rr.body':           'Your average winner (${win}) is smaller than your average loser (${loss}). Classic symptom: you close winners too early out of fear, losers too late in hope. Check the MFE/MAE capture rate.',
    'ci.good_rr.title':         'Solid R:R',
    'ci.good_rr.body':          'Average winner is {rr}x the size of average loser. You let winners run — keep doing that.',
    'ci.narrow_edge.title':     'Edge depends on few trades',
    'ci.narrow_edge.body':      'Only {n} out of {total} trades ({pct}%) make 80% of your gross profit. Lose those outliers (luck? special market phase?) and your performance collapses. Ask yourself: repeatable?',
    'ci.broad_edge.title':      'Broad edge',
    'ci.broad_edge.body':       '{n} of {total} trades carry the profit — no extreme dependency on individual hits. Your edge is robustly distributed.',
    'ci.tilt.title':            'Tilt after losses',
    'ci.tilt.body':             'After a loss your win rate drops from {win}% to {loss}% ({diff}-point difference). Classic revenge-trading indicator. Force a break after 2 consecutive losses.',
    'ci.steady.title':          'Emotional stability',
    'ci.steady.body':           'Your win rate after losses ({loss}%) is nearly identical to after wins ({win}%). You trade independently of the prior outcome — that\'s disciplined trading.',
    'ci.low_capture.title':     'Low profit capture',
    'ci.low_capture.body':      'You capture only {pct}% of the available peak profit on average. Your trades keep running past where you exit — either take-profit too tight or you\'re exiting from fear too early.',
    'ci.high_capture.title':    'Strong profit capture',
    'ci.high_capture.body':     '{pct}% capture — you\'re taking nearly the full peak profit without getting greedy. Clean trade management.',
    'ci.volatile_months.title': 'Volatile months',
    'ci.volatile_months.body':  'High coefficient of variation ({cv}) — your monthly results swing widely. A lottery-win month between flat or red ones is riskier than the total P&L makes it look.',
    'ci.consistent_returns.title': 'Consistent returns',
    'ci.consistent_returns.body':  'CV {cv} with {greens} green months — you deliver evenly, not in waves. That\'s prop-firm worthy.',
    'ci.low_recovery.title':    'Pain bigger than gain',
    'ci.low_recovery.body':     'Recovery factor {rf} — your max drawdown was bigger than your total gain. You had to risk more than you earned.',
    'ci.high_recovery.title':   'High pain efficiency',
    'ci.high_recovery.body':    'Recovery factor {rf} — you earn >5x what you were down at the deepest drawdown. Very robust curve.',
    'ci.high_ror.title':        'Risk too high',
    'ci.high_ror.body':         'Risk of ruin sits at {pct}%. At your current WR/R-ratio and risk size, this isn\'t speculative — it will happen. Reduce risk per trade to <1%.',
    'ci.long_streak.title':     'Long losing streak',
    'ci.long_streak.body':      'Longest losing streak: {n} trades. Make sure your position size can survive that without panic — at 2% risk = ~13% drawdown without compounding.',
    'ci.fallback.title':        'Solid mid-range',
    'ci.fallback.body':         'No extremes at first glance. Look at the individual cards below — the devil\'s in the detail (heatmap timing, tag combos, hold-time distribution).',
  },
}

function interpolate(template, vars) {
  if (!vars) return template
  return template.replace(/\{(\w+)\}/g, (_, key) => (vars[key] != null ? vars[key] : `{${key}}`))
}

/* ─── Provider ─────────────────────────────────────────────── */
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try { return localStorage.getItem(STORAGE_KEY) || 'de' } catch { return 'de' }
  })

  useEffect(() => {
    try { localStorage.setItem(STORAGE_KEY, language) } catch {}
    document.documentElement.lang = language
  }, [language])

  const t = useCallback((key, vars) => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.de
    const fallback = TRANSLATIONS.de
    const template = dict[key] ?? fallback[key] ?? key
    return interpolate(template, vars)
  }, [language])

  const toggle = useCallback(() => {
    setLanguage(prev => prev === 'de' ? 'en' : 'de')
  }, [])

  return (
    <Ctx.Provider value={{ language, setLanguage, toggle, t }}>
      {children}
    </Ctx.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(Ctx)
  if (!ctx) {
    // Safe fallback for the rare case the hook is called outside the provider
    return { language: 'de', setLanguage: () => {}, toggle: () => {}, t: (k) => k }
  }
  return ctx
}
